var post_txt = `
<h1 class="title">আমার অন্তিমযাত্রায়</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">আজ থেকে মানবজনমের আমার কোনো সুখ-দুঃখ নেই;</p>
    <p class="txt center">আজ থেকে মানবজনমের আমার কোনো আশা-আকাঙ্ক্ষা নেই;</p>
    <p class="txt center"><span>আজ থেকে আমি রূপ-রস-গন্ধ-স্পর্শহীন</span><span>—</span></p>
    <p class="txt center">আজ থেকে আমি নিস্তরঙ্গ জলের মতো।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">আজ থেকে আমার নির্ঘুম রাতের প্রহর কাটবে না</p>
    <p class="txt center">প্রিয়তমা কবিতার সুন্দর একটি পঙ্&zwnj;ক্তির প্রসব যাতনায়;</p>
    <p class="txt center">আজ থেকে আমার কণ্ঠস্বর আর ধ্বনিত হবে না কোনোদিন;</p>
    <p class="txt center">আজ থেকে আমার পদচিহ্ন আর পড়বে না পৃথিবীর কোথাও;</p>
    <p class="txt center">আজ থেকে পৃথিবীর কোনো সুন্দর অথবা অসুন্দর</p>
    <p class="txt center"><span>আমাকে ভাবিত করবে না</span><span>—</span></p>
    <p class="txt center">কারণ, আজ থেকে আমি সম্পূর্ণ মৃত।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">আজ আমার বসতবাড়ির বৈঠকখানার খাটিয়াটির ওপর</p>
    <p class="txt center">সদ্য কিনে আনা সাড়ে তিন হাত</p>
    <p class="txt center">ধবধবে সাদা মার্কিন কাপড়ে ঢাকা</p>
    <p class="txt center">আমার প্রাণহীন নিথর শরীর টানটান শোয়ানো;</p>
    <p class="txt center">ঘরময় আগরবাতির ধোঁয়ার গন্ধ থৈ থৈ;</p>
    <p class="txt center">শিয়রের পাশে একটি খোলা পাত্র রক্ষিত, যেন-বা ভিক্ষার ঝুলি;</p>
    <p class="txt center">যার যা ইচ্ছে দিয়ে যাচ্ছে আমার অন্তিমযাত্রার খরচ;</p>
    <p class="txt center"><span>কেউ কেউ রেখে দিয়ে যাচ্ছে আমার নিথর দেহের </span><span>‘</span><span>পর</span></p>
    <p class="txt center">একটি অথবা দুটি ফুল</p>
    <p class="txt center">যাকে কলে কিনা চিরবিদায়ের হয়তো-বা শ্রদ্ধাঞ্জলি</p>
    <p class="txt center">হয়তো-বা ফুলেল শুভেচ্ছা।</p>
    <p class="txt center">কারো কারো চোখ অশ্রুসজল;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center"><span>কারো কারো মুখ বিষণ্ণ</span><span>—</span><span>যেন শ্রাবণের মেঘে ঢাকা আকাশ;</span></p>
    <p class="txt center"><span>আবার, আমাকে নিয়ে কারো কারো কতো কী কথোপকথন</span><span>—</span></p>
    <p class="txt center"><span>কেউ বলছে : </span><span>‘</span><span>লোকটা বড়ো ভালো ছিল</span><span>’</span><span>,</span></p>
    <p class="txt center"><span>কেউ বলছে : </span><span>‘</span><span>আজকাল ভালো হওয়া ভালো নয়</span><span>’</span><span>,</span></p>
    <p class="txt center"><span>কেউ বলছে : </span><span>‘</span><span>লোকটা জীবনে না গাড়ি না বাড়ি না অর্থ</span></p>
    <p class="txt center"><span>কিছুই করতে পারেনি</span><span>’</span><span>,</span></p>
    <p class="txt center"><span>কেউ বলছে : </span><span>‘</span><span>মানবজীবনের মুখ্য উদ্দেশ্যে কিন্তু কেবল তা-ই নয়</span><span>’</span><span>,</span></p>
    <p class="txt center"><span>কেউ বলছে : </span><span>‘</span><span>লোকটা মানুষের মনে বেঁচে থাকবে অনেক দিন;</span><span>’</span></p>
    <p class="txt center">আর, আমার স্বজনেরা নিরর্গল বিরহবৃষ্টির জলে ভিজছে</p>
    <p class="txt center">আর খেদোক্তি করছে প্রিয়বিয়োগ যাতনায়...</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">হে আমার বংশধর,</p>
    <p class="txt center"><span>তোমরা যারা আমার রক্ত ধারণ করে আছো</span><span>—</span></p>
    <p class="txt center">আমি বলছি, তোমরা উত্তম হও, প্রজ্ঞায় হও উদ্ভাসিত;</p>
    <p class="txt center">হে আমার আত্মীয়স্বজন,</p>
    <p class="txt center">তোমরা যারা আমাকে তোমাদের ভালোবাসার নির্যাসে</p>
    <p class="txt center">সিক্ত রেখেছিলে, তোমাদের কাছে আমি ঋণী;</p>
    <p class="txt center">হে আমার চেনা-অচেনা বন্ধুগণ,</p>
    <p class="txt center">তোমরা যারা আমাকে অন্তিম দর্শন করতে এসেছ</p>
    <p class="txt center">এবং সকলে মিলে এই বিদায় সংবর্ধনার আয়োজন করেছ</p>
    <p class="txt center">তার জন্যে তোমাদের সকলকে আমি কৃতজ্ঞতা জানাচ্ছি,</p>
    <p class="txt center">তোমাদের কল্যাণ হোক!</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">আমার নিথর দেহ বাড়ি থেকে উঠোনে নিয়ে আসা হলো;</p>
    <p class="txt center">শেষবারের মতো আমার বাড়ির জলখাবার তুলে দেয়া হলো মুখে;</p>
    <p class="txt center"><span>এবং অতঃপর</span><span>—</span></p>
    <p class="txt center">ঠিক যেন শত্রুর সাথে শত্রুর দূরত্বের ব্যবধানে আমার</p>
    <p class="txt center">আত্মীয়স্বজনের সাথে যাবতীয় সম্পর্ক বিচ্ছেদ ঘটানো হলো;</p>
    <p class="txt center"><span>এখন আমি একা</span><span>—</span><span>বড়ো বেশি একা হয়ে গেলাম</span><span>—</span></p>
    <p class="txt center">পৃথিবীতে যেন আপন বা আমার বলে কিছুই রইলো না আমার;</p>
    <p class="txt center">একাকীত্বের কেমন যেন এক হাহাকারে আমি ক্রমশ ডুবে যাচ্ছি...</p>
    <p class="txt center"><span>এই সুন্দর পৃথিবী ছেড়ে মন আমার যেতে চাইছে না এখন</span><span>—</span></p>
    <p class="txt center"><span>কিন্তু না, আমাকে যে যেতেই হবে</span><span>—</span></p>
    <p class="txt center"><span>সব আয়োজন শেষে কি বলা যায়</span><span>—</span><span>যাবো না, যাবো না!</span></p>
    <p class="txt center">বাক্সবন্দী আমাকে কাঁধে উঠানো হলো,</p>
    <p class="txt center">অনন্তর অন্তিমযাত্রা শুরু হলো আমার, পড়ন্ত বিকেল,</p>
    <p class="txt center"><span>আমার সামনে ও পেছনে কিছু নর আর কিছু নারী</span><span>—</span></p>
    <p class="txt center">ছুটছে যেন-বা বৈরাতীর দল।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">হ্যাঁ, আমি জানতাম, আমাকে একদিন এভাবে চলে যেতে হবে;</p>
    <p class="txt center"><span>আমি যাচ্ছি, যে যাওয়ায় ফিরে আসা নেই</span><span>—</span></p>
    <p class="txt center">যাচ্ছি শূন্যের গভীরতার পানে;</p>
    <p class="txt center"><span>আমি হাঁটছি, যে হাঁটায় কোনো ক্লান্তি নেই</span><span>—</span></p>
    <p class="txt center">হাঁটছি, নিরুদ্দিষ্ট পথিকের মতো;</p>
    <p class="txt center">পৃথিবীর বুকে রেখে যাচ্ছি</p>
    <p class="txt center">হৃদয়ের বিমল সৌন্দর্যে সৃজিত বিবর্ণহীন ছোট্টো এক কবিতাকুঞ্জ;</p>
    <p class="txt center">আমি জেনেছিলাম, মনুষ্যজনম লাভ অতিশয় দুর্লভ</p>
    <p class="txt center">এবং জীবন অতি নশ্বর;</p>
    <p class="txt center">আমি আরও জেনেছিলাম,</p>
    <p class="txt center">ভালোবাসা আর হৃদয়ের সৌন্দর্যের মতো ঐশ্বর্য</p>
    <p class="txt center"><span>মনুষ্যজীবনে আর অন্য কোনো বৈভব নেই</span><span>—</span></p>
    <p class="txt center">মানুষকে আমি হৃদয় নিংড়ানো ভালোবাসার কথা বলেছিলাম,</p>
    <p class="txt center">কল্যাণের কথা বলেছিলাম,</p>
    <p class="txt center">বলেছিলাম আলোকে আলোকিত হওয়ার কথা,</p>
    <p class="txt center">হে পৃথিবীর মানুষ, যদি কোনোদিন কারো ইচ্ছে হয়</p>
    <p class="txt center">তবে প্রবেশে মানা নেই কোনো,</p>
    <p class="txt center">যেতে পারো বেলা কি অবেলায় আমার কবিতাকুঞ্জে</p>
    <p class="txt center"><span>নিতে পারো নিঃসংশয়ে বুকভরা শ্বাস</span><span>—</span></p>
    <p class="txt center">নিতে পারো প্রাণ ভরে কবিতাকুসুমের ঘ্রাণ।</p>
    <p class="txt center"><span>আমি সাথে নিয়ে যাচ্ছি যারা আমাকে প্রাণ খুলে ভালোবাসা দিয়েছিল</span><span>—</span></p>
    <p class="txt center">সেই ভালোবাসা,</p>
    <p class="txt center"><span>যারা আমাকে নিন্দা কিম্বা তাচ্ছিল্য অথবা অবজ্ঞাই দিয়েছিল</span><span>—</span></p>
    <p class="txt center">সেই অবজ্ঞা,</p>
    <p class="txt center">যেই ভালোবাসা আর অবজ্ঞা আমার অন্তরকে বিকশিত করেছিল,</p>
    <p class="txt center">উদ্ভাসিত করেছিল এবং সর্বোপরি</p>
    <p class="txt center">উর্বর করেছিল আমার মানসভূমি;</p>
    <p class="txt center">এবং সাথে নিয়ে যাচ্ছি</p>
    <p class="txt center">অনুগামী নিজস্ব কিছু পাপ অথবা কিছু পুণ্য,</p>
    <p class="txt center">যা আমার সারা মানবজীবনের অর্জিত বিষয়-আশয়।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center"><span>আমাকে এখন নির্ধারিত শ্মশানে পৌঁছানো হলো</span><span>—</span></p>
    <p class="txt center">যেখানে আমার পিতা, যেখানে আমার মাতা</p>
    <p class="txt center">যেখানে আমার পিতামহ-পিতামহী</p>
    <p class="txt center">যেখানে আমার অগ্রজকে</p>
    <p class="txt center">ঠিক এইখানে পৌঁছায়ে দিতে আমি এসেছিলাম,</p>
    <p class="txt center">তারা তখন আমাকে চুপিচুপি কানে কানে বলেছিল,</p>
    <p class="txt center">ঠিকই আমি শুনতে পেয়েছিলাম :</p>
    <p class="txt center">হে প্রিয়, তুমি যা-ই হও অথবা যে-ই হও</p>
    <p class="txt center">এই বেশে এইখানে তোমাকে একদিন আসতে হবে,</p>
    <p class="txt center">এখানে আসতেই হবে তোমাকে;</p>
    <p class="txt center">এবং সত্যিই আমি আজ এখানে এসে গেলাম, ঠিক</p>
    <p class="txt center">আমার পূর্বপুরুষেরা যেই বেশে এখানে এসেছিলেন।</p>
    <p class="txt center">হে আমার পূর্বসূরি, হে চেনা-অচেনা বন্ধুগণ,</p>
    <p class="txt center"><span>নিভৃতচারী আমি এক অধম পথিক, মনুষ্যলোক হতে এসেছি</span><span>—</span></p>
    <p class="txt center">তোমাদের এখানে একটুখানি জায়গা হবে কি আমার?</p>
    <p class="txt center">সবাই আমাকে অভ্যার্থনা জানাতে প্রস্তুত, আমি শুনতে পাচ্ছি :</p>
    <p class="txt center"><span>হে পরিশ্রান্ত পথিক, তোমাকে অভিবাদন</span><span>—</span></p>
    <p class="txt center">জীবন পরিভ্রমণ শেষে তুমি ক্লান্ত,</p>
    <p class="txt center"><span>তুমি নির্দ্বিধায় এসো</span><span>—</span><span>এখানে কোনো শ্রেণিভেদ নেই,</span></p>
    <p class="txt center">আমরা জানি &zwj;তুমি অধম নও।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">আমার নিথর দেহ চিতায় উঠানো হলো,</p>
    <p class="txt center">মুখাগ্নি করা হলো এবং</p>
    <p class="txt center"><span>অতঃপর চিতায় অগ্নিসংযোগ</span><span>—</span></p>
    <p class="txt center">হে অগ্নি, আমি তোমাকেই বলছি,</p>
    <p class="txt center">মৃত্যুই মনুষ্যজীবনের অনিবার্য ও শ্রেষ্ঠতম সত্য বলে জেনেছিলাম,</p>
    <p class="txt center"><span>মৃত্যুবন্দনা করেছিলাম আজীবন</span><span>—</span></p>
    <p class="txt center">মৃত্যুর মতো অনিবার্য সত্যের মহিমায়</p>
    <p class="txt center">মনুষ্যজীবনকে পরিশুদ্ধ করতে চেয়েছিলাম,</p>
    <p class="txt center">আমি নশ্বর জীবনে অবিনশ্বর হতে চেয়েছিলাম,</p>
    <p class="txt center">চেয়েছিলাম কালজয়ী অবিনাশী কবিতার আলোকিত</p>
    <p class="txt center"><span>পঙ্&zwnj;ক্তির মতো মৃত্যুহীন এক প্রশস্য জীবন</span><span>—</span></p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">হে পাবক, এই ইহলোকে আমি আজ মৃত, সম্পূর্ণ মৃত,</p>
    <p class="txt center">মনুষ্যজন্মের অন্তিম সত্যের নীলিমায় একাকার,</p>
    <p class="txt center">আমার যত অশুভ-অশুচি সমর্পিত এখন তোমার করতলে,</p>
    <p class="txt center"><span>আমার পায়ের নখ হতে মাথার চুল অবধি তোমার হাতের মুঠোয়</span><span>—</span></p>
    <p class="txt center">নিঃশেষিত করো নিমেষে এই আমাকে,</p>
    <p class="txt center">হে সর্বনাশা, তোমার প্রলয়দাহনে...</p>
    <p class="txt center">দাউ দাউ করে জ্বলে উঠলো চিতা,</p>
    <p class="txt center">অগ্নিস্ফুলিঙ্গ আমাকে স্পর্শ করলো</p>
    <p class="txt center">আর, যারা আমাকে এখানে পৌঁছায়ে দিতে এসেছে</p>
    <p class="txt center"><span>অসহায়ের মতো তারা নিরুপায় চেয়ে আছে আমার দিকে</span><span>—</span></p>
    <p class="txt center">হ্যাঁ, আমি তোমাদের বলছি,</p>
    <p class="txt center">হে বন্ধুগণ,</p>
    <p class="txt center">আমাকে এখানে পৌঁছায়ে দেওয়ার জন্যে তোমাদের ধন্যবাদ,</p>
    <p class="txt center">তবে মনে রেখো, তোমরাও এই পথেরই পথিক।</p>
    <p class="txt center">এবং অতঃপর,</p>
    <p class="txt center">প্রজ্বলন্ত অনলের নিষ্ঠুর প্রবল দাহনে</p>
    <p class="txt center">মোমের মতো গলে গলে</p>
    <p class="txt center">একজন দৃশ্যমান আমি ও আমিত্বের সকল অহংকার</p>
    <p class="txt center">ছাইপাঁশ হয়ে শায়িত হলো ভূতল শয্যায়,</p>
    <p class="txt center">অবিরাম আগামীর জন্যে...</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">... কে তুমি? কে তুমি ভাবছো আমার কথা?</p>
    <p class="txt center">নীরবে ফেলছো চোখের জল?</p>
    <p class="txt center"><span>আমিও তো কাঁদিয়াছি তোমার লাগি</span><span>—</span></p>
    <p class="txt center">দেখো নাই আমার গহীন অন্তরতল।</p>
    <p class="txt center"><span>তোমা হতে আমি আজ দূরে</span><span>—</span><span>বহু দূরে,</span></p>
    <p class="txt center"><span>না জানি ছুটছি কোথা</span><span>—</span></p>
    <p class="txt center">কোন সে-জগৎ পানে;</p>
    <p class="txt center"><span>আমার লাগি কাঁদিও না হে আমার প্রিয়</span><span>—</span></p>
    <p class="txt center">খুঁজিও নির্জন নিরালায়,</p>
    <p class="txt center">খুঁজিও আমার কবিতা ও গানে। </p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">তোমার শততম জন্মদিনে</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">হে প্রভু,</p>
    <p class="txt center">আজি ২০১৯ খ্রিষ্টাব্দের জানুয়ারি আট</p>
    <p class="txt center">২৫ শে পৌষ, বাংলা ১৪২৫ সাল;</p>
    <p class="txt center"><span>শীতের শিশিরসিক্ত হিমেল প্রভাত</span><span>—</span></p>
    <p class="txt center">কুয়াশারা চারিদিকে মেলেছে যেন ধবলিয়া পাল।</p>
    <p class="txt center">পাখিরা সেই কখন ঘুম হতে উঠেছে জেগে,</p>
    <p class="txt center">তরুশাখে কিবা তলে ক্রীড়ারত শাখামৃগ দল,</p>
    <p class="txt center">বায়ু বহিছে হিম হিম অতি মন্থর বেগে;</p>
    <p class="txt center">তব স্মৃতিভরা অভয় উদ্যান রাজবনে নেমেছে আজি পূজারীর ঢল।</p>
    <p class="txt center"><span>সাজিয়াছে রাজবন</span><span>—</span><span>আহা, কী রূপ! অপরূপ সাজ;</span></p>
    <p class="txt center">কর্তব্যনিষ্ঠ প্রণম্য তব শিষ্যমণ্ডলী, সৌম্য শান্ত যেন-বা তোমার মুরতি;</p>
    <p class="txt center"><span>পূজ্য ও পূজারীর অনিন্দ্যসুন্দর মহামিলনের শুভদিন আজ</span><span>—</span></p>
    <p class="txt center">বিনম্র শ্রদ্ধায় প্রণত সবে, হে প্রভু, তোমার প্রতি।</p>
    <p class="txt center">হে প্রভু,</p>
    <p class="txt center">আজিকে তব শততম শুভ জন্মদিন;</p>
    <p class="txt center">আজি হতে শতবর্ষ আগে</p>
    <p class="txt center">ধরণীর বুক করিয়া রঙিন</p>
    <p class="txt center">এসেছিলে এই দিনে পৌষের প্রভাত অরুণরাগে</p>
    <p class="txt center">আপনারে সিক্ত করি;</p>
    <p class="txt center">সেই হতে শতবর্ষ পরে</p>
    <p class="txt center">তব সেই আগমনবার্তাখানি মোরা আজো নির্ভয়ে পড়ি,</p>
    <p class="txt center">আলোকঝরনাধারা হয়ে ঝরে ঝরে পড়ে</p>
    <p class="txt center">সেই হতে আজি শতবর্ষ ধরে।</p>
    <p class="txt center">হে প্রভু,</p>
    <p class="txt center"><span>আজি হতে শতবর্ষ আগে</span><span>—</span></p>
    <p class="txt center">পার্বত্য চট্টলার মগবান মৌজার মোরঘোনা গ্রামে</p>
    <p class="txt center">হারুমোহন-বীরপুদির ঘরে এই দিনে কী আনন্দ-কোলাহল জাগে,</p>
    <p class="txt center"><span>জন্ম নিল শিশুপুত্র এক</span><span>—</span><span>এই তুমি বনভন্তে, সেই রথীন্দ্র নামে।</span></p>
    <p class="txt center">কে-বা জানিত তখন</p>
    <p class="txt center">শান্তির দূত তুমি আসিয়াছ দেবলোক হতে,</p>
    <p class="txt center"><span>কে-বা জানিত ভরিবে তোমার আলোয় জগৎ-ভুবন</span><span>—</span></p>
    <p class="txt center"><span>দিশাহারা জনে দেখাবে দিশা</span><span>—</span><span>ভাসাবে সুখের স্রোতে।</span></p>
    <p class="txt center"><span>বর্ষ যায়, বর্ষ আসে</span><span>—</span></p>
    <p class="txt center">সেই তুমি রথীন্দ্র শিশু থেকে বালক, তারপর বয়স যদিও কিশোর</p>
    <p class="txt center">সদ্ধর্মে মতিস্থৈর্য প্রকাশে;</p>
    <p class="txt center"><span>অতঃপর যৌবনে তুমি, পরম সুখ সন্ধানে বিভোর</span><span>—</span></p>
    <p class="txt center">তুমি জেনেছিলে জীবন দুঃখময়;</p>
    <p class="txt center">জেনেছিলে তৃষ্ণার শৃঙ্খলে জন্ম-জন্মান্তর,</p>
    <p class="txt center">ত্যাগই একমাত্র পথ দুঃখ করিবারে জয়;</p>
    <p class="txt center">তাই আপনারে তৃষ্ণামুক্ত করিতে অতঃপর</p>
    <p class="txt center"><span>জীবনসূর্যের ভরা যৌবন হতে সন্ন্যাসব্রত থাকি অস্ত অবধি</span><span>—</span></p>
    <p class="txt center">দিবস-রজনী যায়, বর্ষ পরে বর্ষ হয় গত,</p>
    <p class="txt center">সাগরের টানে ছুটে যেমন নদী</p>
    <p class="txt center">ছিলে দুঃখমুক্তির কঠোর সাধনারত;</p>
    <p class="txt center">অবশেষে,</p>
    <p class="txt center"><span>পশিল নদী সাগরে এসে</span><span>—</span></p>
    <p class="txt center">রুদ্ধ হলো তব সব ইন্দ্রিয়দ্বার,</p>
    <p class="txt center">আপনাতে হলে লোভ-দ্বেষ-কামনা-বাসনাহীন;</p>
    <p class="txt center">দীপশিখা জ্বলে উঠবার শঙ্কা নাহি আর,</p>
    <p class="txt center">অসীমে অসীম হয়ে আপনাতে হলে লীন;</p>
    <p class="txt center">হৃদয়ে পশিল তোমার মুক্তির বার্তাখানি,</p>
    <p class="txt center"><span>ত্যাগদীপ্ত চিত্তে সকল তৃষ্ণার হলো অবসান</span><span>—</span></p>
    <p class="txt center">মানবেরে শুধালে অমরবাণী,</p>
    <p class="txt center">শুধালে তোমার পরম সুখের গান।</p>
    <p class="txt center">তোমার সুনিবিড় ছায়াতলে ছিল যেইজন,</p>
    <p class="txt center">নিজেরে সে নিজে চিনে নিয়েছিল তারে;</p>
    <p class="txt center">তোমার অমৃতবাণীসুধা পান করে নাই কখন</p>
    <p class="txt center">জানে না সে নিমজ্জিত কত অন্ধকারে;</p>
    <p class="txt center"><span>ত্যাগদীপ্ত সুখে আজীবন প্রচারি</span><span>’</span><span> সদ্ধর্মের অমিয় বাণী</span></p>
    <p class="txt center">২০১২ খ্রিষ্টাব্দের জানুয়ারি ৩০-শে লভেছিলে পরিনির্বাণ;</p>
    <p class="txt center">অধমেরে বলেছিলে, অমলে নির্মল কর আপন চিত্তখানি,</p>
    <p class="txt center"><span>প্রজ্ঞালোকে ঋদ্ধ করি</span><span>’</span><span> আপনারে, দুঃখরে কর অবসান।</span></p>
    <p class="txt center">হে প্রভু,</p>
    <p class="txt center"><span>মহীরুহ হয়ে আজীবন দিয়ে গেছ ছায়া</span><span>—</span></p>
    <p class="txt center">দিয়ে গেছ সুবাসিত ফুল,</p>
    <p class="txt center">দিয়ে গেছ রসে ভরা ফল</p>
    <p class="txt center">যার আস্বাদ অমৃত তুল।</p>
    <p class="txt center">তুমি যে কেবল বিলিয়েই গেছ</p>
    <p class="txt center">আপনার তরে চাহ নাই কিছু,</p>
    <p class="txt center">পার্থিব সুখ তরে ছুটো নাই কভূ</p>
    <p class="txt center">ষড়রিপুভরা এ সংসার পিছু।</p>
    <p class="txt center">তুমি যে ছিলে অচল-অটল</p>
    <p class="txt center">চঞ্চল হেন অধীর হও নাই কভূ,</p>
    <p class="txt center"><span>তুমি যে ছিলে মহাশান্তির দূত</span><span>—</span></p>
    <p class="txt center">ছিলে সকল জীবের প্রভু।</p>
    <p class="txt center">হে প্রভু,</p>
    <p class="txt center"><span>নির্ঝর হয়ে বয়ে গেছ সদা</span><span>—</span></p>
    <p class="txt center">দিয়ে গেছ স্বচ্ছ শীতল জল,</p>
    <p class="txt center"><span>পান করি</span><span>’</span><span> অধমে মিটাল তৃষা</span><span>—</span></p>
    <p class="txt center">জুড়াল তাপিত বক্ষতল।</p>
    <p class="txt center">রবি হয়ে উঠেছিলে আঁধারের বুকে</p>
    <p class="txt center">চারিদিক ছড়ায়ে তোমার কর,</p>
    <p class="txt center">আলোর পরশে জাগিল অধমে</p>
    <p class="txt center">দীপ্ত করিল আপনারে অতঃপর।</p>
    <p class="txt center"><span>সেই আলো আজও সদা দীপ্তিময়</span><span>—</span></p>
    <p class="txt center">কে সে জন বলে তুমি হেথা নাহি,</p>
    <p class="txt center"><span>সেই অমৃতরস মোরা করি পান</span><span>—</span></p>
    <p class="txt center">সেই নির্ঝর জলে মোরা অবগাহি।</p>
    <p class="txt center"><span>তব সেই ছায়া আজও ছায়াময়</span><span>—</span></p>
    <p class="txt center">সেই ফুল আজও বিলায় সুবাস,</p>
    <p class="txt center">সেই ফল আজও রসময়</p>
    <p class="txt center">পান করে মিটাই মনের তিয়াস।</p>
    <p class="txt center"><span>তুমি যে ছিলে আলোর প্রতীক</span><span>—</span></p>
    <p class="txt center">ছিলে দুঃখমুক্তির দিশারী,</p>
    <p class="txt center">তব অবদান মোরা কী কভূ</p>
    <p class="txt center">জনমে জনমে ভুলিতে পারি?</p>
    <p class="txt center">হে প্রভু,</p>
    <p class="txt center">জানি, তুমি আর আসিবে না ফিরে</p>
    <p class="txt center">প্রাণ হয়ে এই প্রাণসাগরতীরে,</p>
    <p class="txt center">অসীম শূন্যে তব চির অধিবাস;</p>
    <p class="txt center">রেখে গেছ হেথা পবিত্র দেহধাতুখানি,</p>
    <p class="txt center"><span>সাথে তার অহিংস অবিনাশী বাণী</span><span>—</span></p>
    <p class="txt center">আলো হয়ে আছো সদা আমাদের চারিপাশ।</p>
    <p class="txt center">অভয় উদ্যান রাজবনে নিয়ত আসিয়া পূজারী</p>
    <p class="txt center">তব সকাশে দিয়া পরাণ উজারি</p>
    <p class="txt center">কত জনে কত কী মাগে বর,</p>
    <p class="txt center">কত জনে তব দেহধাতু পূজিবারে আসে,</p>
    <p class="txt center">কত জনে হৃদয়ের যাতনা নাশে</p>
    <p class="txt center">পশিয়া হৃদে তার তব উজ্জ্বল কর।</p>
    <p class="txt center"><span>বর্ষ যাইবে</span><span>—</span><span>বর্ষ আসিবে,</span></p>
    <p class="txt center"><span>মানবসকল তব স্তুতি গাহিবে</span><span>—</span></p>
    <p class="txt center">কত যুগ কত কাল হইবে গত,</p>
    <p class="txt center">চিরস্মরণীয় মহান মানব তুমি</p>
    <p class="txt center">রচে গেলে ভুবনে নতুন এক পুণ্যভূমি</p>
    <p class="txt center">সময়ের বুকে জ্বলজ্বলে নক্ষত্রের মত।</p>
    <p class="txt center">হে প্রভু,</p>
    <p class="txt center">আজি তব শততম শুভ জন্মদিন,</p>
    <p class="txt center"><span>উৎসবে উৎসবে মুখরিত</span><span>—</span></p>
    <p class="txt center">চারিদিক আনন্দ-রঙিন;</p>
    <p class="txt center">পৌষের হিম হিম গেল মাঝরাত হতে</p>
    <p class="txt center">আসিয়া পূজারী অবিশ্রান্ত স্রোতে</p>
    <p class="txt center"><span>জনে জনারণ্য আজি রাজবন তুমি</span><span>—</span></p>
    <p class="txt center"><span>দিকে দিকে তাই</span><span>⸺</span><span>শুনিতে যে পাই</span></p>
    <p class="txt center">সবার হৃদয়ে তুমি।</p>
    <p class="txt center"><span>যার পানে চাই</span><span>⸺</span><span>আনন্দ উছলায়</span></p>
    <p class="txt center">নাহি কোনো শঙ্কা</p>
    <p class="txt center">নাহি কোনো ভীতি,</p>
    <p class="txt center"><span>শুনি শুধু তব বন্দনাগীতি</span><span>—</span></p>
    <p class="txt center"><span>তোমার উজ্জ্বল করে</span><span>⸺</span><span>মানবহৃদয় </span><span>’</span><span>পরে</span></p>
    <p class="txt center">আলোকপুষ্প উঠিল ফুটি,</p>
    <p class="txt center"><span>তোমার আলোর জোয়ার</span><span>⸺</span><span>ভাঙিল বদ্ধ দুয়ার</span></p>
    <p class="txt center">গেল রে আঁধার টুটি।</p>
    <p class="txt center"><span>আজিকার মত শুভদিন</span><span>⸺</span><span>কভূ না হোক মলিন</span></p>
    <p class="txt center">থাক সবার হৃদয়ে নিতি,</p>
    <p class="txt center"><span>আজিকার দিবসের মত</span><span>⸺</span><span>থাক অবিরাম অবিরত</span></p>
    <p class="txt center">মৈত্রী-করুণা-প্রীতি।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">নমঃ প্রভু নমঃ নমঃ</p>
    <p class="txt center">আজি তব শততম</p>
    <p class="txt center"><span>শুভ শুভ শুভ জন্মতিথি</span><span>—</span></p>
    <p class="txt center">আশীর্বাদ মাগি হে প্রভু,</p>
    <p class="txt center">দিগ্&zwnj;ভ্রম যেন কারো না ঘটে কভূ,</p>
    <p class="txt center">আঁধার যেন না ঘেঁষে বুকে</p>
    <p class="txt center">সবে যেন থাকে সুখে,</p>
    <p class="txt center">থাকে যেন সদ্ধর্ম সদ্&zwnj;কর্ম নীতি।</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">ছোঁয়া ও আলোর পরশ</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">কোন্ জনমের পুণ্য ফলে মানব জনম পেলে,</p>
    <p class="txt center">জন্ম কি আর হয়রে সফল বৃথাই যদি গেলে?</p>
    <p class="txt center">পলে পলে দিন যে ফুরোই টের পেলে না হায়!</p>
    <p class="txt center">কত জনম এলোরে গেলো হিসাব যে তার নাই।</p>
    <p class="txt center">জলের ধারা বয়রে কেন সব নদী তা জানে,</p>
    <p class="txt center">স্রোতের টানে যায়রে জীবন এগোয় মরণ পাণে।</p>
    <p class="txt center">চাওয়া যত অবিরত বাড়ায় মনের সাধ,</p>
    <p class="txt center">চাওয়ার মাঝে নাই যে পাওয়া সকল সাধই বাঁধ।</p>
    <p class="txt center">মনটা তোমার, তোমার কাছেই ইচ্ছা মতন ঘুরাও,</p>
    <p class="txt center">ঘড়ির নাটায় তোমার হাতে মনের মতন উড়াও।</p>
    <p class="txt center">ধন্য করো জীবন খানি ছোঁয়াও আলোর পরশ</p>
    <p class="txt center">শূণ্য দিয়ে পূর্ণ করো তোমার মনের কলস।</p>
    <p class="txt center">দুঃখ তব শূন্য হলে রইলে না আর আশা</p>
    <p class="txt center">রইবে না আর এপার ওপার তোমার যাওয়া আসা ॥</p>
    <p class="txt center">সাধু-সাধু-সাধু</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">আর্য শ্রেষ্ঠ বনভন্তের প্রতি</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">হে দেব, তিমির বিনাশী অবিনাশী আলো তুমি</p>
    <p class="txt center">কোন্ সে স্বর্গ হতে মানবরূপে এসেছ মর্ত্যভূমি</p>
    <p class="txt center">বিলাইতে তব মঙ্গল আলোক,</p>
    <p class="txt center">অতৃপ্ত তৃষ্ণার নিকষ আঁধারে ঢাকা</p>
    <p class="txt center">লোভ-মোহ-ক্রোধ-হিংসায় মাখা</p>
    <p class="txt center">যাতনায় কাতর সদা এ ভুলোক।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center"><span>মোহের পেছনে চিরকাল হেথা ছুটিল</span><span>’</span><span>রে মানুষ</span></p>
    <p class="txt center">স্বার্থ দ্বন্দ্বের আঘাতে সংঘাতে মাতাল বেহুশ</p>
    <p class="txt center">কোন কালে কভু তার মিটিল না সাধ,</p>
    <p class="txt center">স্বর্গের শান্তির দূত তুমি আসিয়াছ হেথা</p>
    <p class="txt center">সাথে লয়ে স্বর্গের শান্তির মহাবারতা</p>
    <p class="txt center">মানবেরে দিতে ত্যাগের মহিমা-আস্বাদ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">স্বার্থের দাবানল নিত্য জ্বলিছে মানবসমাজে</p>
    <p class="txt center">চারিদিকে দাউ দাউ হিংসা কেবলি বিরাজে</p>
    <p class="txt center">অসুরে সতত করিছে হু হুংকার,</p>
    <p class="txt center">মানবতার এহেন দুঃসময়ে তোমার বাণী-</p>
    <p class="txt center">সুখী হউক সুখী হউক জগতের সকল প্রাণী-</p>
    <p class="txt center">ধ্বনিতেছে তব মুখে বারংবার।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">মানবে মানবে হেথা অবিরাম হানাহানি</p>
    <p class="txt center">আলোকের পথে তাদেরে আনিবারে টানি</p>
    <p class="txt center">দিবস-রজনী তুমি রয়েছ ব্রত,</p>
    <p class="txt center">প্রত্যহ তব আকাশে অগণন নর-নারী আসি</p>
    <p class="txt center">চিরসুখী হতে চায় সকল দুঃখ রাশি</p>
    <p class="txt center">শুনিয়া তব বাণী অমৃতের মত।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">নির্ঝর যেন তব নির্মল আলোক উৎস হতে</p>
    <p class="txt center">বহমান করুণাধারা অবিশ্রান্ত স্রোতে</p>
    <p class="txt center">সত্যসুন্দর সুমধুর অমৃতের বাণী,</p>
    <p class="txt center">পাপতাপদগ্ধ মুমূর্ষ নর-নারী গণে-</p>
    <p class="txt center">করিতেছে পান প্রশান্ত তৃপ্ত মনে</p>
    <p class="txt center">জুড়াইছে তার তাপিত পরাণখানি।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">বর্ষ পরে বর্ষ থাকিয়া সাধনায় রত</p>
    <p class="txt center">করিয়াছ জয় জগতের অশুভ অমঙ্গল যত</p>
    <p class="txt center">করিয়াছ আপনারপ সকল বন্ধনহীন,</p>
    <p class="txt center">নক্ষত্রের মত তুমি আজি চির ভাস্বর।</p>
    <p class="txt center">তোমার আলোক রাশি ম্লানহীন অবিনশ্বর</p>
    <p class="txt center">কাল হতে কালে তুমি অক্ষয় অমলিন।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">অসীম আগামী হতে কালস্রোত আসি</p>
    <p class="txt center">বহিছে অসীম অতীতের পানে</p>
    <p class="txt center">কত কাল কত প্রাণ আসিয়া গিয়াছে।</p>
    <p class="txt center">কালের শাশ্বত আহ্বানে-</p>
    <p class="txt center">আসিতেছে নিরন্তর আজো সেই আহ্বান,</p>
    <p class="txt center">তুমি অতীত নও-চলমান নও-</p>
    <p class="txt center">নও তুমি অনাগত আগামী</p>
    <p class="txt center">সব ইন্দ্রিয় দ্বার রুদ্ধ করি</p>
    <p class="txt center">যত আয়োজন তব গিয়াছে থামি-</p>
    <p class="txt center">স্থির নক্ষত্র তুমি এক সতত জ্যোতিষ্মান।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">হে প্রভু, অবোধ আমি বিনম্র চিত্তে করি প্রার্থনা</p>
    <p class="txt center">দাও শকতি, দূর করি প্রমত্ত জীবন যন্ত্রণা</p>
    <p class="txt center">পূর্ণ করিবারে চাই আপনারে দুঃখ-মুক্তি জ্ঞানে,</p>
    <p class="txt center">প্রতিরূপ দেশে জন্ম লভি যেন জনমে জনমে</p>
    <p class="txt center">মোহের ইন্দ্রজালে কভু না পড়ি সুখের ভ্রমে</p>
    <p class="txt center">চিত্তের গতি থাকে যেন সতত উর্দ্ধ পানে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">নাহি জানি কতকাল কিবা রূপে আসিয়া গিয়াছি চলে</p>
    <p class="txt center">ভ্রমিতেছি জন্ম হতে জন্মান্তর আপন কর্মফলে</p>
    <p class="txt center">নাহি জানি কত দীর্ঘ এই কন্টকাকীর্ণ পথ,</p>
    <p class="txt center">হে প্রভু, দাও আশীর্বাদ দূর করিবারে অন্ধকার-</p>
    <p class="txt center">কৃপা করি দাও শকতি রুদ্ধ করি দ্বার-</p>
    <p class="txt center">পূর্ণ কর হে প্রভু অভাগার মনোরথ ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">ভ্রান্ত পথে ধাবমান শিশুতুল্য মানব অবোধ</p>
    <p class="txt center">লোভ-মোহ ভারাক্রান্ত অন্তরের অগ্নিসম ক্রোধ</p>
    <p class="txt center">পাপীজন পাপগ্লানি দূর করিবারে চায়,</p>
    <p class="txt center">হে প্রভু, হে দেব, দাও নির্বোধেরে সুমতি</p>
    <p class="txt center">পাপাচার ছাড়ি অনুগত থাকে যেন পঞ্চ ধর্মের প্রতি</p>
    <p class="txt center">আশীর্বাদ তব অধমে যেন জন্মান্তরে পায়।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">যতদিন রবে মানুষের মাঝে মানুষের ভেদাভেদ</p>
    <p class="txt center">দ্বন্দ্ব-সংঘাত মানবে মানবে ঘটাইবে ব্যবচ্ছেদ</p>
    <p class="txt center">রহিবে ততদিন অশান্ত জগৎ-ধরণী,</p>
    <p class="txt center">বিশ্বমানবে একসুরে যবে গাহিবে মৈত্রীর গান</p>
    <p class="txt center">শান্তির সূর্য উঠিবে তবে নিশি করি অবসান-</p>
    <p class="txt center">অহিংস নীতি শান্তির বিশল্যকরণী।</p>
    <p class="txt center">হে প্রভু আর্য শ্রেষ্ঠ, সকল কালের সকল দিনে</p>
    <p class="txt center">সকল মানব নিজেরে যেন নিতে পারে চিনে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">আসিয়া তব আলোক পরশে,</p>
    <p class="txt center">চারিদিকে ধ্বনিত হউক সদা অহিংসার জয়মঙ্গলগীতি</p>
    <p class="txt center">কারো মনে কভু নাহি থাক শঙ্কা-নাহি থাক ভীতি</p>
    <p class="txt center">ভরা থাক সকল প্রাণ অমৃতরসে।</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">বুদ্ধ গৌতম</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">(এক)</p>
    <p class="txt center">আজি হতে আড়াই সহস্র বর্ষ আগে,</p>
    <p class="txt center">হিমালয় কোলে কপিলাবস্তু রাজা শুদ্ধোদন তনয় তুমি</p>
    <p class="txt center">মহারাণী মায়াদেবী গর্ভে জন্ম তোমার।</p>
    <p class="txt center">নাম সিদ্বার্থ-</p>
    <p class="txt center">যে কুমার তুমি</p>
    <p class="txt center">রাজ্য-সিংহাসনধন-ঐশর্য্য শ্রী যশোধরা পুত্র রাহুল</p>
    <p class="txt center">মায়ার বন্ধন ছিন্ন করি,</p>
    <p class="txt center">জ্ঞানের অন্বেষণ হেতু করেছিলে গৃহত্যাগ,</p>
    <p class="txt center">কি অপূর্ব আশ্চর্য মহিমা তোমার।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">সর্বজীবের দুখে দুঃখী</p>
    <p class="txt center">বহুজন সুখের তরে</p>
    <p class="txt center">বর্ষ পরে বর্ষ কঠোর সাধনা করেছিলে তুমি,</p>
    <p class="txt center">ষষ্ঠ বর্ষ পরে উজ্জ্বল আলোক রশ্মির পেয়েছিলে সন্ধান</p>
    <p class="txt center">বিচ্ছুরিত রাশি রাশি আলোক-জ্যোতির</p>
    <p class="txt center">উৎস করেছিলে আবিষ্কার -</p>
    <p class="txt center">মহামানব তুমি এক</p>
    <p class="txt center">সকল কিছুর উর্ধে, আপনাকে করেছিলে জয়,</p>
    <p class="txt center"><span>অনন্ত-অসীম সীমাহীন তুমি </span><span>–</span></p>
    <p class="txt center">অমৃত জ্ঞানালোক শিখা অনির্বাণ,</p>
    <p class="txt center">বুদ্ধ দীপংকর হতে চারি অসংখ্য লক্ষ কম্প বর্ষ পরে</p>
    <p class="txt center">অন্ধকার জগতে বুঝিয়া সেই প্রথম সূর্যোদয় -</p>
    <p class="txt center">তুমি সেই বুদ্ধ গৌতম।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">তথাগত, সর্বজ্ঞানের অধিকারী তুমি</p>
    <p class="txt center">তোমা হতে আজি সহস্র বর্ষ পরে</p>
    <p class="txt center">সহস্র বর্ষ হয়েছে গত,</p>
    <p class="txt center">তোমার অমৃত বাণীর অমিয়ধারা বহে আজো</p>
    <p class="txt center">প্রাণে প্রাণে</p>
    <p class="txt center">দেশে দেশে</p>
    <p class="txt center">কাল হতে কালে স্রোতস্বিনী যেন</p>
    <p class="txt center">অবিরল ধারাজল অনন্ত উৎস হতে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">নিজেই নিজের প্রভূ; ষড় রিপু জয় করে যেই জন</p>
    <p class="txt center">পরম সুখ তার ইহপর কালে; ভোগই দুঃখের কারণ</p>
    <p class="txt center">ত্যাগেই সুখ, তোমার অমৃত বাণী,</p>
    <p class="txt center">তৃষ্ণার শৃংখলে শৃংখলিত জন্ম-জন্মান্তর</p>
    <p class="txt center">তৃষ্ণার প্লাবনে বার বার</p>
    <p class="txt center">ফিরে আসা এ জগৎ-সংসারে</p>
    <p class="txt center">একটি তৃষ্ণা জন্ম দেয় অজস্র দুঃখের</p>
    <p class="txt center">জন্মে জন্মে খেলে যাওয়া শুধু দুঃখ-দুঃখ খেলা।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">দূর্লভ অতিশয় মানব জনম</p>
    <p class="txt center">মানবের হিতার্থে আলোকিত রাজপথ</p>
    <p class="txt center">একমাত্র তুমিই করেছিলে নির্মাণ,</p>
    <p class="txt center">নাম তার দুঃখ-মুক্তি তথা নির্বাণ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">তোমার প্রচারিত বৌদ্ধধর্ম নাম</p>
    <p class="txt center">বিশ্বজন নন্দিত তোমার অহিংসা-মৈত্রীর বাণী :</p>
    <p class="txt center">নমো বুদ্ধ নমো ধর্ম নমো সংঘ</p>
    <p class="txt center">আমি সতত জানাই প্রণাম।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">(দুই)</p>
    <p class="txt center">ভগবান, বুদ্ধ ভগবান,</p>
    <p class="txt center">তুমি অনন্ত মহান,</p>
    <p class="txt center">কি গাইব তোমারই গুণগান।</p>
    <p class="txt center">দূর-বহুদূর,</p>
    <p class="txt center">বিপুল সুদুর</p>
    <p class="txt center">হতে সদা আসিতেছে ভাসি</p>
    <p class="txt center">রাশিরাশি</p>
    <p class="txt center">তোমার মধুর বাণী,</p>
    <p class="txt center">মানবের তরে দিতেছে আনি,</p>
    <p class="txt center">অমৃত-নিৰ্কর হতে অতধারা</p>
    <p class="txt center">লোভ-মোহদ্বেষ তমসায় যারা -</p>
    <p class="txt center">জ্বেলে দাও তুমি জ্ঞানের আলো।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">দূর করে দাও আঁধার কালো।</p>
    <p class="txt center">অমৃতালোক দিয়াছ বিছায়ে</p>
    <p class="txt center">সারা বিশ্বময় আছে ছড়ায়ে,</p>
    <p class="txt center">প্রতিদিন</p>
    <p class="txt center">নিশিদিন</p>
    <p class="txt center">তোমার বিমল-আনন্দ-পুলক ধারা</p>
    <p class="txt center">বহিছে সারা</p>
    <p class="txt center">বিশ্বময়,</p>
    <p class="txt center">হে জ্যোতির্ময়,</p>
    <p class="txt center">আছ হৃদয় গভীরে, প্রাণের মাঝারে</p>
    <p class="txt center">আলোক বিলাও তুমি নিশীথ আঁধারে-</p>
    <p class="txt center">ভগবান, বুদ্ধ ভগবান</p>
    <p class="txt center">কি করে গাইব তোমারই গুণগান।</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">বনভন্তের স্মরণে নিবেদিত পঙক্তিমালা</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">হে প্রভু,</p>
    <p class="txt center">অন্তিম শয়নে আজিকে শায়িত তুমি</p>
    <p class="txt center">রাজবন অহিংস অভয় কাননে,</p>
    <p class="txt center">দলে দলে নিয়ত পূজারীর ঢল</p>
    <p class="txt center">পূজিতে তোমারে ব্যাকুল-বাসনা মনে।</p>
    <p class="txt center">শিষ্যমণ্ডলী তব অতন্দ্র তপস্যারত</p>
    <p class="txt center">পার্থিব যত কামনা-বাসনা ত্যাগি',</p>
    <p class="txt center">গুরু বিহনে শোকাতুর প্রাণ</p>
    <p class="txt center">কাঁদে অহিংস অনুত্তর ধর্মানুরাগী।</p>
    <p class="txt center">বায়ু বেগে তব পরিনির্বাণ বারতা</p>
    <p class="txt center">দিক হতে দিকে ছুটিল সহসা,</p>
    <p class="txt center">গগনে গগনে ঘন মেঘের ঘনঘটা</p>
    <p class="txt center">নিমেষে নামিল অঝোরে বিরহ বরষা।</p>
    <p class="txt center"><span>পূজারীর হাতে শোকভারনত কুসুমের তোড়া</span><span>—</span></p>
    <p class="txt center">হৃদয়ে বেদনা বহতা নদী,</p>
    <p class="txt center">বেদনা-বিদীর্ণ হতো কি পরাণ</p>
    <p class="txt center">আমাদের ছেড়ে না যেতে যদি?</p>
    <p class="txt center">২০১২ সাল জানুয়ারি ৩০</p>
    <p class="txt center"><span>অপরাহে ৩টা ৫৬ সোমবার</span><span>—</span></p>
    <p class="txt center">তব পরিনির্বাণের এই মহাক্ষণে</p>
    <p class="txt center">বৌদ্ধজাতির কি কভূ ভুলিবার?</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">হে প্রভু,</p>
    <p class="txt center">তৃষ্ণার দীপশিখা তব গিয়াছে নিভিয়া</p>
    <p class="txt center">জ্বলিবে না কভূ তা ক্ষণিকের তরে,</p>
    <p class="txt center">জন্মান্তর ব্যূহচক্র হতে মুক্তি লভিয়া,</p>
    <p class="txt center">আপনারে করিলে বিলীন নিঃশেষ করে ।</p>
    <p class="txt center">অনন্তের পানে যেমনি বহে মহাকাল</p>
    <p class="txt center">পুনঃ ফিরে যাহা আসিবারে নয়,</p>
    <p class="txt center">অসীমের মাঝে তুমিও হয়েছ অসীম</p>
    <p class="txt center">তব পুনঃ জনমের নাহি ভয়।</p>
    <p class="txt center">প্রপাতের বারিধারা হেন অবিরল</p>
    <p class="txt center">শুধায়েছ অধমেরে শান্তির বাণী,</p>
    <p class="txt center">বিপথগামীরে সুপথে তুমি</p>
    <p class="txt center">করুণায় সহসা এনেছিলে টানি'।</p>
    <p class="txt center">ভোগই মানবের চিরদুঃখের হেতু</p>
    <p class="txt center"><span>ত্যাগেই জীবনে পরম শান্তি মিলে</span><span>—</span></p>
    <p class="txt center">জীবন ত্যাগিয়া কঠোর সাধনা সাধিয়া</p>
    <p class="txt center">মহাসত্যের পথ দেখিয়ে দিলে।</p>
    <p class="txt center">তব আলোকধারায় আলোকিত ধরা</p>
    <p class="txt center">এ আলোক সলিলে মোরা অবগাহি,</p>
    <p class="txt center">জনমে জনমে এ মঙ্গলালোকে</p>
    <p class="txt center">আপনারে পূর্ণ রাখিবারে চাহি।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">হে প্রভু,</p>
    <p class="txt center">তব স্মৃতিভরা এ অভয় উদ্যানে</p>
    <p class="txt center">বিহঙ্গদলে আজো গাহে গান,</p>
    <p class="txt center">সুনিবিড় তরুশাখে শাখামৃগশিশু</p>
    <p class="txt center">নির্ভয়ে করে মাতৃদুগ্ধ পান।</p>
    <p class="txt center">প্রতিদিন আজো ওঠে হেথা নবীন সূর্য</p>
    <p class="txt center">আলোয় আলোয় ভরা এ তীর্থভূমি,</p>
    <p class="txt center">নিত্য নব পূজারী আসে পুণ্যস্নানে</p>
    <p class="txt center">হৃদয়ে হৃদয়ে জাগরিত তুমি।</p>
    <p class="txt center">যে আলোকবর্তিকা দিয়া গেছ জ্বালিয়া</p>
    <p class="txt center">প্রজ্বলিত সূর্যের মতো শিখা অনির্বাণ,</p>
    <p class="txt center">দিশাহারা পান্থ খুঁজে পায় পথের দিশা-</p>
    <p class="txt center">আলোর দিশারী তুমি চির দ্যুতিমান।</p>
    <p class="txt center">মন-বাতায়ন পথে স্মৃতির উতলা সমীর</p>
    <p class="txt center">প্রাণ ছুঁয়ে ছুঁয়ে ধীরে যায় বহি,</p>
    <p class="txt center">নয়ন সমুখে মূর্ত তুমি, কথা নাহি কও,</p>
    <p class="txt center">তব এ নীরবতা এ অধম কেমনে সহি?</p>
    <p class="txt center">হৃদয়-কন্দর হতে উৎসারিত বিমূঢ় শব্দপুঞ্জ</p>
    <p class="txt center"><span>একে একে সযতনে গাঁথিয়া মালা</span><span>–</span></p>
    <p class="txt center">সকল দিবসের মতো সাজাইলাম আজিকে</p>
    <p class="txt center">হে প্রভু,</p>
    <p class="txt center">তব তরে, এই মম শ্রদ্ধার্ঘ্য ডালা।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">বেলা যখন বাড়ল</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">অনেক ভেতর থেকে কে যেন বললেঃ</p>
    <p class="txt center">-দরোজা জানালা সব বন্ধ করে দাও।</p>
    <p class="txt center">সেই কবে থেকেই</p>
    <p class="txt center">আমার ঘরের</p>
    <p class="txt center">দরোজা জানালার কপাট খোলাই ছিল।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">একটা জানালার পাশে দাঁড়িয়ে</p>
    <p class="txt center">বাইরের দৃশ্যে তাকাচ্ছিলুম,</p>
    <p class="txt center">জানালা পথে হু হু করে ঢুকছে হাওয়া</p>
    <p class="txt center">নাকে চোখে মুখে</p>
    <p class="txt center">লাগছে ঝড়ের ছোঁয়া।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">বেলা বাড়তে থাকে-</p>
    <p class="txt center">বাড়তে থাকে আমার বয়স;</p>
    <p class="txt center">ভাবছিলুমঃ</p>
    <p class="txt center">দরোজা জানালা বন্ধ রাখাই ভাল।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">এমন সময়-</p>
    <p class="txt center">বাইরে থেকে কে যেন বললেঃ</p>
    <p class="txt center">জন্মান্ধ কি জানে বৃক্ষের পাতারা সবুজ?</p>
    <p class="txt center">আর-সমুদ্রের রং আকাশের মত নীল?</p>
    <p class="txt center">ভেতর থেকে আবার ঐ কণ্ঠস্বরঃ</p>
    <p class="txt center">-দরোজা জানালা সব বন্ধ করে দাও।</p>
    <p class="txt center">বেলা যখন বাড়ল-টের পেলুম</p>
    <p class="txt center">মনের দরোজা জানালা বন্ধ রাখাটাই ভাল।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center"><br class="calibre1">উত্তর পুরুষের জন্য রচিত পঙক্তিমালা</p>
    <p class="txt center">(আত্মজ শ্রী ডরিন তালুকদারকে)</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">১.</p>
    <p class="txt center">মহীরুহ হয়ে সুশীতল ছায়া দিও</p>
    <p class="txt center">দুঃখ দিনে দিও অভয় আশ্বাস</p>
    <p class="txt center">মেঘ হয়ে চৈত্রদিনে দিও জল</p>
    <p class="txt center">বুকের ভিতরে গড়ো নিরাপদ আবাস</p>
    <p class="txt center">২.</p>
    <p class="txt center">ফুল থেকে নিও কিছু ঘ্রাণ</p>
    <p class="txt center">নিও প্রাণখোলা হাসি</p>
    <p class="txt center">ঝর্ণার কাছ থেকে নিও কলতান</p>
    <p class="txt center">সাগরের কাছ থেকে নীল রাশিরাশি।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">৩.</p>
    <p class="txt center">জ্যোৎস্নার কাছ থেকে নিও কোমলতা</p>
    <p class="txt center">সূর্য থেকে নিও আলো মুঠো মুঠো</p>
    <p class="txt center">অসময়ের অন্ধকারে আলো জ্বেলে।</p>
    <p class="txt center">অরুণ হয়ে ওঠো।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">৪.</p>
    <p class="txt center">পৃথিবীর সৌন্দর্য্যের সব উপমা</p>
    <p class="txt center">আকণ্ঠ আহরণ করো।</p>
    <p class="txt center">মহাপুরুষের মত যেন বেঁচে থাক চিরকাল</p>
    <p class="txt center">এমনই জীবন গড়ো।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">৫.</p>
    <p class="txt center">সময়ের কাজ থেকে নিও কিছুটা সময়</p>
    <p class="txt center">সময়ের হাত ধরে যেতে পারো যেনো</p>
    <p class="txt center">নদীর কাছ থেকে শিখে নিও কিভাবে বয়ে যেতে হয়</p>
    <p class="txt center">মরণে নতুন জীবন এনো।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">৬.</p>
    <p class="txt center">মানব জনম বহু সাধনায় পাওয়া</p>
    <p class="txt center">যে কোন সময় হারাতে পারো</p>
    <p class="txt center">সময়ের হেলা না করে সামনে এগো</p>
    <p class="txt center">সন্দেহ তাই এ সময় পাবে কিনা আবারো।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">৭.</p>
    <p class="txt center">জীবনে শুধু চাওয়া আর পাওয়া নয়</p>
    <p class="txt center">কিছু না কিছু দিয়ে যেতে হবে</p>
    <p class="txt center">পৃথিবীতে মানুষ হয়ে জন্মেছ যখন</p>
    <p class="txt center">মানুষের মত কাজ করে যাও তবে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">৮.</p>
    <p class="txt center">জীবনের আয়ু দ্রুত বয়ে যায়</p>
    <p class="txt center">তাই যতদিন দেহে থাকে প্রাণ</p>
    <p class="txt center">নদী হয়ে নিরলস অবিরাম বয়ে যাও</p>
    <p class="txt center">পৃথিবীতে বেঁচে থাক চির অম্লান।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">৯.</p>
    <p class="txt center">ফুল হও ফল হও বীজ হও</p>
    <p class="txt center">হও মেঘ হও নদ-নদী</p>
    <p class="txt center">ভোরের পাখি হয়ে কণ্ঠে ধরো গান</p>
    <p class="txt center">ঝর্ণা হয়ে পাহাড় ভেঙে বও নিরবধি।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">১০.</p>
    <p class="txt center">সময়ের সকল বাধ ভাঙতেই হবে</p>
    <p class="txt center">গেয়ে যেতেই হবে জীবনের গান</p>
    <p class="txt center">মনুষ্য জীবন সার্থক তবেই হবে</p>
    <p class="txt center">সত্যের পথে যদি যায় যাক প্রাণ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">১১.</p>
    <p class="txt center">আজীবন জ্ঞান আহরণ করো</p>
    <p class="txt center">জ্ঞানী-গুণীদের জীবনী থেকে</p>
    <p class="txt center">মরণের পরে সময়ের বুকে</p>
    <p class="txt center">রেখে যাও স্মরণ চিহ্ন এঁকে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">১২.</p>
    <p class="txt center">পৃথিবীতে অস্ত্রের খেলা খেলতে দিও না আর</p>
    <p class="txt center">জগতে চিরশান্তি নিয়ে আসো।</p>
    <p class="txt center">বুদ্ধের অহিংসা মৈত্রী করুণার</p>
    <p class="txt center">আলো জ্বেলে সকল অন্ধকার নাশো।।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">সিঁড়ি</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">আমি আমার মৃত্যুর কথা ভাবছিলাম,</p>
    <p class="txt center">ভাবতে ভাবতে আমার সমগ্র চেতনা</p>
    <p class="txt center">ধীরে ধীরে কেন্দ্রীভূত হচ্ছিল আমার মৃত্যুতে,</p>
    <p class="txt center">সমস্ত আমিত্বের মিনার মোমের মত গলে গলে পড়ছিল,</p>
    <p class="txt center">এক সময় আমি মৃত্যুর ভেতর একাকার হয়ে গেলাম।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">আমি অনুভব করছিলাম</p>
    <p class="txt center">অন্ধকারের দেয়াল ভাঙতে ভাঙতে</p>
    <p class="txt center">উজ্জ্বল আলোর সিড়ি বেয়ে ক্রমশ উপরে উঠছি এবং উঠছি</p>
    <p class="txt center">এবং বোধের বীজগুলো অংকুরিত হচ্ছে চেতনার মৃত্তিকায়;</p>
    <p class="txt center">অন্ধকার থেকে উঠে আসা আমার এক পরম</p>
    <p class="txt center">বিশ্বাসের ভেতর আমার অস্তিত্ব অনুভব করলাম মনে হল,</p>
    <p class="txt center">এই প্রথম আমাকে আমি নির্মাণ করলাম আমার বিশ্বাসে</p>
    <p class="txt center">আমার মৃত্যু চেতনার আলোকিত জগতে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">মৃত্যু আমাকে বলছিল</p>
    <p class="txt center">আমি তোমার পরম ঘনিষ্ঠতম সখা,</p>
    <p class="txt center">তোমার সমগ্র অস্তিত্বে আমার বসবাস</p>
    <p class="txt center">তোমার জন্মতেই আমার জন্ম;</p>
    <p class="txt center">তোমাতে আমার অস্তিত্ব অনুভব কর</p>
    <p class="txt center">আমাতেই তোমার জীবনের পরিপূর্ণতা দাও।</p>
    <p class="txt center">অবশেষে আমার মৃত্যুতে অনুভব করলাম আমার যাবতীয় অপরাধবোধ,</p>
    <p class="txt center">আমার লোভ, মোহ এবং অহংকার চূর্ণ হতে লাগল,</p>
    <p class="txt center">আমার অনুভবে উপলব্ধি করলাম সৌন্দর্য্যের মহিমা</p>
    <p class="txt center">হে মৃত্যু, তুমি সতত জাগরিত থাক আমার চেতনায়</p>
    <p class="txt center">আমার বিশ্বাসে এবং অস্তিত্বে।।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">গীতি কবিতা</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">আমি মানুষ হইয়া জনম লইয়া</p>
    <p class="txt center">মানুষ হইলাম না,</p>
    <p class="txt center">তৃষ্ণার গাঙে নাও ভাসাইয়া</p>
    <p class="txt center">কিনারা তার পাইলাম না,</p>
    <p class="txt center">আমি কিনারা তার পাইলাম না ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">কতজনা এলোরে গেলো</p>
    <p class="txt center">নদীর চরে ঘর বানাইলো,</p>
    <p class="txt center">স্রোতের তোড়ে ভেঙ্গে গেলো</p>
    <p class="txt center">খবর কেউ তার রাখলো না,</p>
    <p class="txt center">তৃষ্ণার গাঙে নাও ভাসাইয়া</p>
    <p class="txt center">কিনারা তার পাইলাম না ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">সারা জীবন বৈঠা বহিলাম</p>
    <p class="txt center">কত আশায় দিন কাটাইলাম,</p>
    <p class="txt center">আশায় আশায় জীবন গেলো</p>
    <p class="txt center">আসল-নকল চিনলাম না,</p>
    <p class="txt center">তৃষ্ণার গাঙে নাও ভাসাইয়া</p>
    <p class="txt center">কিনারা তার পাইলাম না।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">আসলাম একা যাবোও একা</p>
    <p class="txt center">কত জনার সঙ্গে হইল দেখা।</p>
    <p class="txt center">দিন ফুরালে যেতে হবে</p>
    <p class="txt center">সঙ্গী আমার কেউ হবে না,</p>
    <p class="txt center">তৃষ্ণার গাঙে নাও ভাসাইয়া</p>
    <p class="txt center">কিনারা তার পাইলাম না,</p>
    <p class="txt center">আমি মানুষ হইয়া জনম লইয়া</p>
    <p class="txt center">মানুষ হইলাম না।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">এসো হে সুন্দর</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">তুমি জান আমি জানি</p>
    <p class="txt center">শুধু কেহ নাহি মানি</p>
    <p class="txt center">এ জীবন শুধু পলকের দেখাও;</p>
    <p class="txt center">এই জনমের শেষে</p>
    <p class="txt center">নাহি জানি কেবা কোথা যাব মিশে</p>
    <p class="txt center">কর্ম লিখনে কার কি আছে লেখা।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">শুধু দু'দিনের তরে আসিয়াছি হেথা,</p>
    <p class="txt center">তবু হায়, মুহুর্তের তরে সুখ নাহি কোথা</p>
    <p class="txt center">মানবে মানবে যত দলাদলি;</p>
    <p class="txt center">হিংসার দাবানল তুষানল সম জ্বলে।</p>
    <p class="txt center">দুর্বলেরে হানিছে আঘাত সদা সবলে</p>
    <p class="txt center">আপন অনলে মরিছে আপনাতে জ্বলি ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">মানব অন্তরে কেন এত লোভ</p>
    <p class="txt center">কিবা রোষে জাগে কেন বা ক্ষোভ</p>
    <p class="txt center">মানবের মাঝে কেন এত ভেদাভেদ;</p>
    <p class="txt center">আপনার স্বার্থ পূর্ণ করিবারে</p>
    <p class="txt center">সুন্দরেরে বলি দিতে সে পারে</p>
    <p class="txt center">বাড়ায় কেবলই মনের বিষসম খেদ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">হে অবুঝ অবোধ মানব সন্তান</p>
    <p class="txt center">দিতে পারি নাই কভু আপনি আপনারে সম্মান</p>
    <p class="txt center">গাও এবে মানবের মহামিলনের গান;</p>
    <p class="txt center">কত দূর মানবের যত ব্যথা, যত না বন্ধন</p>
    <p class="txt center">অন্তরে অন্তরে দৃঢ় হোক মানব বন্ধন</p>
    <p class="txt center">গড়, হে মানব, এ সত্য স্বর্গ সমান।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">মনের বাগিচায় ফুটাও নিত্য নব পুষ্প রাশি</p>
    <p class="txt center">আপনারে পূর্ণ কর সকলেরে ভালবাসি;</p>
    <p class="txt center">আপনার পদাবদাহ আপনাতে করিব অবসান;</p>
    <p class="txt center">মানবে মানবে বিলাও তব কুসুম সুবাস</p>
    <p class="txt center">আপনাতে গড় তুমি সুখের নিবাস</p>
    <p class="txt center">তোমার সুখের মাল্য সকলেরে কর দান।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">এসো হে, এসো হে সুন্দর তম</p>
    <p class="txt center">মানবের অন্তরে এসো অমৃতের ফলধারাসম</p>
    <p class="txt center">বিশ্ব মাঝে ঢালো তব সুবিমলধারা;</p>
    <p class="txt center">হোক দূর যত ক্ষোভ, যত ভেদাভেদ</p>
    <p class="txt center">নিমিষে বিলীন হোক বিষময় খেদ</p>
    <p class="txt center">তব সঙ্গলাভে সুখী হোক পথহারা যারা।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">মানব জনম অতি দুর্লভ এই ধরাতলে</p>
    <p class="txt center">কোথা হতে আসে কোথা যায় চলে</p>
    <p class="txt center">সময়ের স্রোতে অসীমের পানে;</p>
    <p class="txt center">কর নির্মল হে চির সুন্দর-</p>
    <p class="txt center">পূর্ণ কর তব রূপে মানব অন্তর</p>
    <p class="txt center">শান্ত কর এ বিশ্ব তব মঙ্গল গানে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">মরণ আমার জীবন সখা</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">(১)</p>
    <p class="txt center">মরণ তোমারে দেখেছি আমি</p>
    <p class="txt center">জেনেছি তোমারে জেনেছি,</p>
    <p class="txt center">তুমি যে আমার জীবন-সহচর</p>
    <p class="txt center">জনমের সাথী করে এনেছি।</p>
    <p class="txt center">তুমি যে আমার পরম সখা</p>
    <p class="txt center">দোহে মোরা করি ঘর,</p>
    <p class="txt center">তুমি যে মোরে নিয়ে যাবে ওপার</p>
    <p class="txt center">এ পারের সবকিছু করি পর।</p>
    <p class="txt center">তুমি যে মানবের পরম বন্ধু</p>
    <p class="txt center">চরম শত্রুও বটে,</p>
    <p class="txt center">তুমি যে নিয়ে যাও ওপার</p>
    <p class="txt center">সকলেরে বিফল মনোরথে।</p>
    <p class="txt center">হে আমার জীবন সখা</p>
    <p class="txt center">বল, কেন এত পাষাণ হলে?</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">(২)</p>
    <p class="txt center">মিটিতে সাধ ভেঙ্গে দাও খেলা</p>
    <p class="txt center">পিষে চরণ তলে।</p>
    <p class="txt center">কত যে খেলা ভাঙিয়া দিয়াছ</p>
    <p class="txt center">নিভায়ে দিয়াছ আশা,</p>
    <p class="txt center">চুরমার করে দিয়াছ কত যে স্বপন</p>
    <p class="txt center">কত যে মনের কত ভালবাসা।</p>
    <p class="txt center">জানিয়াছি তুমি কত নির্মম</p>
    <p class="txt center">বুঝিয়াছি কত যে নিঠুর,</p>
    <p class="txt center">তুমি যে শুধু কেবলই কাঁদাও</p>
    <p class="txt center">দিয়া যাতনা বেদনাবিধুর।</p>
    <p class="txt center">হে সখা, তুমি যে কেবল তোমাতে ডাকো</p>
    <p class="txt center">তবু কেন এত আশা, বুঝি নাকো,</p>
    <p class="txt center">কেন জাগে মনে এত সাধ-</p>
    <p class="txt center">আসিয়া যদি ফিরে যেতে হবে</p>
    <p class="txt center">আপনার বলে যদি কিছু নাহি রবে</p>
    <p class="txt center">তবে কেন এই তৃষ্ণার বাঁধ?</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">(৩)</p>
    <p class="txt center">তুমি বিনা এ জগতে কেহ নাহি আসে</p>
    <p class="txt center">জান না তো সে নিজেরে কত ভালবাসে</p>
    <p class="txt center">তবু তুমি কাহারেও ছাড় নাহি দাও,</p>
    <p class="txt center">এ তব কেমন খেলা খেল তুমি নিতি</p>
    <p class="txt center">নিজ গৃহ কর নাশ একি তব রীতি-</p>
    <p class="txt center">বল, এ খেলায় কিবা সুখ তুমি পাও?</p>
    <p class="txt center">যে বন্ধু, তব কথা ভেবে ভেবে</p>
    <p class="txt center">মোর তৃষ্ণার দীপ যাক আজিকে নিভে-</p>
    <p class="txt center">আপনাতে জ্বালাইব নির্মল আলো;</p>
    <p class="txt center">আলোকে আলোকে পূর্ণ করি আপনারে</p>
    <p class="txt center">তারপর বিলাইব নিকষ আঁধারে</p>
    <p class="txt center">অন্ধজনে এ ধরায় বাসিয়া ভালো।</p>
    <p class="txt center">জনমে জনমে কোন জনে যেন</p>
    <p class="txt center">অন্তর গহীন না জ্বলে তুষানল হেন</p>
    <p class="txt center">ভোগে চরম শোকে,</p>
    <p class="txt center">তব কথা ভাবে যেন সকল মানব</p>
    <p class="txt center">থাকুক হিংসা বিদ্বেষ হেন হিংস্র দানব</p>
    <p class="txt center">পূর্ণ হোক মর্ত্যভূমি মঙ্গল আলোকে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">মন</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">মন কারো-বা চপল হওয়া</p>
    <p class="txt center">যার ঠিকানা নাই জানা,</p>
    <p class="txt center">সবখানে তার অবাধ গতি</p>
    <p class="txt center">কোথাও যেতে নেই মানা।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">মন কারো-বা মাটির কলস</p>
    <p class="txt center">ছিদ্রে ভরা যাহার তল,</p>
    <p class="txt center">পূর্ণ তবু হয় না কভূ</p>
    <p class="txt center">যতই তাতে ভরুক জল ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">মন কারো-বা সুখের আধার</p>
    <p class="txt center">সুখ থাকে তার নিত্য,</p>
    <p class="txt center">জীবনে সে হয় কভূ</p>
    <p class="txt center">লোভের মোহের ভৃত্য।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">মন কারো-বা বেজায় গরম</p>
    <p class="txt center">অনল যেন গনগনে;</p>
    <p class="txt center">মন কারো-বা বরফ শীতল</p>
    <p class="txt center">মাঘের মত কনকনে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">মন কারো-বা অথৈ পাথরে</p>
    <p class="txt center">উথাল পাতাল ঢেউ</p>
    <p class="txt center">পার ভাঙ্গে তার হরহামেশা</p>
    <p class="txt center">যা দেখে না কেউ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">মন কারো-বা বটের ছায়া-</p>
    <p class="txt center">অচল যেন ধীর;</p>
    <p class="txt center">ধ্যানমগ্ন ঋদ্ধ পুরুষ</p>
    <p class="txt center">তার মত নেই বীর।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">মন কারো-বা হরেক রকম</p>
    <p class="txt center">যেমন মেঘের রং</p>
    <p class="txt center">রং মেখে সে রং বদলায়</p>
    <p class="txt center">যেন নাট্যশালার সঙ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">কালের খাতায় নাম লিখতে হলে</p>
    <p class="txt center">চায় আলোর মত মন,</p>
    <p class="txt center">দেহ সে তো কালের আহার</p>
    <p class="txt center">বলেন মুক্তপুরুষগণ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">তব জীবন পাত্র</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">(১)</p>
    <p class="txt center">মিছে যে স্বপন<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>গভীর মগন</p>
    <p class="txt center">তুমি যে রহিলে রত,</p>
    <p class="txt center">মনে যত আশ<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>শুধু দীর্ঘশ্বাস</p>
    <p class="txt center">বাড়িল যাতনা ক্ষত।</p>
    <p class="txt center">ব্যাকুল বাসনা<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>গভীর যাতনা</p>
    <p class="txt center"><span>আছাড়ি</span><span>’</span><span> আছাড়ি পড়ে,</span></p>
    <p class="txt center">নাহি মিটে সাধ<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>অন্তর বিষাদ</p>
    <p class="txt center">কেবলি কাঁদিয়া মরে।</p>
    <p class="txt center">মন যত পায়<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>আরো তত চায়</p>
    <p class="txt center">কামনা বিলাপে কহে,</p>
    <p class="txt center"><span>“</span><span>আরো বেশী চাই<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></span><span>মোর কিছু নাই-</span></p>
    <p class="txt center">অন্তর অনলে দহে।</p>
    <p class="txt center">আছে এত ধন<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>শত লোকজন</p>
    <p class="txt center">আশা তবু না ফুরায়,</p>
    <p class="txt center">বুকে এত জল<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>সমুদ্র অতল</p>
    <p class="txt center">তৃষ্ণা তবু নাহি যায় ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">(২)</p>
    <p class="txt center">মন যাহা আশে<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>কাছে নাহি আসে</p>
    <p class="txt center">মন তবু পেতে চায়,</p>
    <p class="txt center">সাগরের বুকে<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>কি জানি কি সুখে</p>
    <p class="txt center">তরঙ্গ খেলিয়া যায় ।</p>
    <p class="txt center">কত যে রাজন<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>করিল শাসন</p>
    <p class="txt center">সদম্ভ সদর্প ভরে,</p>
    <p class="txt center">কিছু নাহি পেল<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>ভরা ডুবি গেল</p>
    <p class="txt center">সময়ের গহ্বরে !</p>
    <p class="txt center">তবু তুমি মিছে<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>দুরাশার পিছে</p>
    <p class="txt center">লোভ মোহ পানে ধাও,</p>
    <p class="txt center">সুখ চাই বলি<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>দিন যায় চলি</p>
    <p class="txt center">সুখ কভু নাহি পাও।</p>
    <p class="txt center">আশা যত বাড়ে<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>দুঃখ নাহি ছাড়ে</p>
    <p class="txt center">বিফলে জনম যায়,</p>
    <p class="txt center">জীবন অনিত্য <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>মৃত্যু চিরসত্য</p>
    <p class="txt center">কেহ মানিতে না চায়।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">(৩)</p>
    <p class="txt center">মূর্খ নাহি বুঝে<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>দুঃখ নাহি ঘুচে</p>
    <p class="txt center">তাই পূনঃ ফিরে আসা</p>
    <p class="txt center">পুর্নজন্ম লয়ে<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>ভব এ আলয়ে</p>
    <p class="txt center">মিছে কাঁদা আর হাসা।</p>
    <p class="txt center">এ কেমন মন<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>ভরে না কখন</p>
    <p class="txt center">বহিয়া যায় রে বেলা,</p>
    <p class="txt center">কর সমাপন<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>রঙিন স্বপন</p>
    <p class="txt center">সাঙ্গ কর হে এ খেলা।</p>
    <p class="txt center">জ্ঞানী জনে বলে<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>ত্যাগি' সুখী হলে</p>
    <p class="txt center">সুখ চিরকাল রয়,</p>
    <p class="txt center"><span>ত্যাগি</span><span>’</span><span> সুখী হও<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>চিরসুখী রও</span></p>
    <p class="txt center">তব তৃষ্ণা কর ক্ষয়।</p>
    <p class="txt center">ছাড়িয়া কুমতি<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>জগতের জ্যোতি</p>
    <p class="txt center">হয়ে রও চিরকাল,</p>
    <p class="txt center">আলোকিত হও<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>মৃত্যুঞ্জয়ী রও</p>
    <p class="txt center">জয় কর মহাকাল।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">(৪)</p>
    <p class="txt center">হিংসা নিন্দা লোভ<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>ভেদাভেদ ক্ষোভ</p>
    <p class="txt center">মন থেকে কর দূর,</p>
    <p class="txt center">কর দূর পানি<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>অমৃতের বানী</p>
    <p class="txt center">কর পান সুমধূর ।</p>
    <p class="txt center">ক্ষণিকের সুখ<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>বাড়ে জনম দুখ</p>
    <p class="txt center">দুঃখ কর পরিহার,</p>
    <p class="txt center">খুলো এ বাঁধন<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>কর হে সাধন</p>
    <p class="txt center">ভব নদী হও পার।</p>
    <p class="txt center">জন্ম মৃত্যু নদী<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>যদি নিরবধি</p>
    <p class="txt center">বহে কাল হতে কাল,</p>
    <p class="txt center">জন্মান্তর তব<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>রূপে নব নব</p>
    <p class="txt center">জড়াবে দুখের জাল।</p>
    <p class="txt center">সুখ যত চাহ<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>বাড়ে তাপ দাহ</p>
    <p class="txt center">সুখ বলে কিছু নাই,</p>
    <p class="txt center">জনমে জনমে<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>ভ্রমিতেছে ভ্রমে</p>
    <p class="txt center">তব পুনর্জন্ম তাই ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">(৫)</p>
    <p class="txt center">জ্ঞানী জনে কহে<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>ত্যাগি নাহি দহে</p>
    <p class="txt center">জন্ম মৃত্যু হন পার,</p>
    <p class="txt center">আছে প্রানী যত<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>জন্মান্তর গত</p>
    <p class="txt center">অনিত্য এ সংসার।</p>
    <p class="txt center">যায় দিন ক্ষণ<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>সমূখে মরণ</p>
    <p class="txt center">সদাই আসিছে তেড়ে,</p>
    <p class="txt center">পাবে না সময়<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>মিছে কভূ নয়</p>
    <p class="txt center">প্রাণ তব নেবে কেড়ে !</p>
    <p class="txt center">কর সদা পান<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>অমৃতের সমান</p>
    <p class="txt center">জ্ঞানীগুণী জন বানী,</p>
    <p class="txt center">রবি চন্দ্র করে<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>লহ তুমি ভরে</p>
    <p class="txt center">জীবনের পাত্রখানি।</p>
    <p class="txt center">ভোগ আশা ছাড়ি<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>জীবন কান্ডারি</p>
    <p class="txt center">জয়মাল্য পরে গলে,</p>
    <p class="txt center">নাহি কোন ভয়<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>আসিলে সময়</p>
    <p class="txt center">হাসি মুখে যেও চলে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">তৃষ্ণার প্লাবনে ফিরে ফিরে আসা</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">মায়ামৃগের পেছন-পেছন কেবলই ধাওয়া;</p>
    <p class="txt center">তৃষ্ণার বৈঠা হাতে</p>
    <p class="txt center">জীবনভর বেয়ে যাওয়া দুঃখের তরী;</p>
    <p class="txt center">অথচ</p>
    <p class="txt center">মানুষ নিজেই নিজের দুঃখ জন্ম দেয়</p>
    <p class="txt center">এবং জন্ম মাত্রই দুঃখ, এটা বুদ্ধষিত বাণী,</p>
    <p class="txt center">বীজ থেকে অংকুর</p>
    <p class="txt center">তারপর বৃক্ষ</p>
    <p class="txt center">বৃক্ষ থেকে মহীরুহ-</p>
    <p class="txt center">দুঃখ কেবলই দুঃখ জন্ম দেয়</p>
    <p class="txt center">তৃষ্ণাই জন্ম দেয় রোগ শোক যত দুঃখবোধ</p>
    <p class="txt center">এক জন্ম থেকে বহু জন্ম</p>
    <p class="txt center">শৃঙ্খলিত জন্ম জন্মান্তর তৃষ্ণার শৃঙ্খলে;</p>
    <p class="txt center">এবং</p>
    <p class="txt center">পক্ষান্তরে, মানুষ নিজেই নিজের মুক্তিদাতা।</p>
    <p class="txt center">তবুও মানুষ ছুটে তৃষ্ণার অন্ধকার অরণ্যের দিকে</p>
    <p class="txt center">সযত্নে পুষে রাখে বুকের ভেতর</p>
    <p class="txt center">ললিত বাসনা-</p>
    <p class="txt center">সূর্যোদয় থেকে সন্ধ্যা অবধি;</p>
    <p class="txt center">আবারো সূর্যোদয়</p>
    <p class="txt center">আবারো সন্ধ্যা,-</p>
    <p class="txt center">এভাবে বারবার</p>
    <p class="txt center">ফিরে ফিরে আসা</p>
    <p class="txt center">একই প্রস্থান বিন্দুতে</p>
    <p class="txt center">তৃষ্ণার ঘোলা জলের প্রাবনে।।</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">প্রার্থনা</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">তোমার বন্দনা করি, হে প্রভু, হে চির জ্যোতিষ্মান</p>
    <p class="txt center">আমি নরাধম, গন্তব্য অচিন দিগচিহ্নহীন</p>
    <p class="txt center">তিমির আঁধার তক জন্মান্তর হয়েছে বিলীন</p>
    <p class="txt center">এইকালে তব জ্ঞানসুধা চাই করিবারে পান।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">লোভ-ক্রোধ-মোহ-হিংষা-বিদ্বেষ আপণ বৈরী যত</p>
    <p class="txt center">দূর করিবারে চাই, তব অমর অমৃত বাণী</p>
    <p class="txt center">রসে পূর্ণ করিবারে চাই মোর শূন্য পাত্রখানি</p>
    <p class="txt center">দাও আশীর্বাদ চিত্ত মম থাক সতত সংযত।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">হে প্রভু গৌতম, অনাথের নাথ, চির জ্যোতির্ময়</p>
    <p class="txt center"><span>দাও গো শক্তি প্রাণে</span><span>—</span><span>থাকি যেন সতত অবিচল</span></p>
    <p class="txt center">তব জ্ঞানে লভি যেন জনম অসীম পুণ্যময়</p>
    <p class="txt center">অহিংস বাণীস্নাত থাকুক চিত্ত অবিরল।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">হে প্রভু, আমি এ অধম মনুষ্যজন্ম ইহকাল</p>
    <p class="txt center">চাই তব জ্ঞানে পূর্ণ করিবারে কিম্বা পরকাল।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">মৃত্যু আমার আজন্ম সহচর</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">হে মৃত্যু, আমি জেনেছি</p>
    <p class="txt center"><span>তুমি আমার শত্রু নও</span><span>—</span></p>
    <p class="txt center">তোমাকে নিয়ে আমি যতবার ভেবেছি,</p>
    <p class="txt center">তুমি বলেছো :</p>
    <p class="txt center"><span>তুমি স্থির হও</span><span>—</span></p>
    <p class="txt center">ঠিক যেন শীত-সকালের পুকুরের শান্ত জলের মত,</p>
    <p class="txt center"><span>তুমি বিনম্র হও</span><span>—</span></p>
    <p class="txt center">ঠিক যেন বর্ষার জলভারনত কোমল মেঘের মত,</p>
    <p class="txt center">তুমি বলেছো :</p>
    <p class="txt center">এই তোমার প্রকৃষ্ট সময়,</p>
    <p class="txt center"><span>নির্মল করো অগ্নির মত চিত্তের যত জঞ্জাল</span><span>—</span></p>
    <p class="txt center"><span>বিশাল সিন্ধু</span><span>—</span><span><span>বিন্দু বিন্দু করো  ক্ষয়</span></span><span>,</span></p>
    <p class="txt center">তারপর হও তুমি অনাগত মহাকা...</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">আমি তোমাকে বলছি :</p>
    <p class="txt center">তুমি আমার আজন্ম সহচর,</p>
    <p class="txt center">তুমি মৃত্যু আমি জন্ম এক সাথে</p>
    <p class="txt center">এই দেহে বাঁধিয়াছি ঘড়।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">তুমি বিনা এ জনমের</p>
    <p class="txt center">কোনো মূল্য নাহি;</p>
    <p class="txt center">উত্তাল সমুদ্রতটে বাঁধিয়াছি তরী,</p>
    <p class="txt center">শীতল স্বচ্ছ নির্ঝর জলে</p>
    <p class="txt center">আমি অবগাহি।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">রাত্রি শেষে</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">লড়ায়ের খেলা চলে এখানে</p>
    <p class="txt center">বিশ্বব্রহ্মাণ্ডের এই পৃথিবী নামক গ্রহে</p>
    <p class="txt center">নিজ নিজ স্বার্থের টানে</p>
    <p class="txt center">মানুষের বুকে মানুষ কী নির্মম আঘাত হানে!</p>
    <p class="txt center">মানুষ মানুষে ভেদাভেদ</p>
    <p class="txt center"><span>থেকেই যাবে কি চিরকাল?</span><span>—</span></p>
    <p class="txt center">মানুষের বুকে আজ হৃদয়ের দারুণ আকাল!</p>
    <p class="txt center">একজন মানুষ আর কতটুকু</p>
    <p class="txt center">নিতে পারে সয়ে,</p>
    <p class="txt center"><span>মুরুবুকে ক্ষীণধারা নদী যায় বয়ে</span><span>—</span></p>
    <p class="txt center">এক একটি সুন্দর সকাল</p>
    <p class="txt center">অসহায় মানুষের কাছে</p>
    <p class="txt center">হয়ে ওঠে বিষণ্ন বিকাল।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">জানি না, স্বার্থের কী এত বিশাল প্রয়োজন,</p>
    <p class="txt center">দিকে দিকে দেখি তাই</p>
    <p class="txt center">লড়াইয়ের বিপুল আয়োজন।</p>
    <p class="txt center"><span>এখানে জীবন আর মৃত্যুরকী ভীষণ টানাটানি</span><span>—</span></p>
    <p class="txt center">এখানে কি কিছূই হবে না?</p>
    <p class="txt center"><span>কত না লড়াই চলে</span><span>—</span><span>কত হানাহানি,</span></p>
    <p class="txt center">পৃথিবীতে বড় অদ্ভুদ এই দ্বিপদ প্রাণী।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">জানী, চৈত্রের শেষে বৈশাখ আসে,</p>
    <p class="txt center">কচি পাতারা জাগে</p>
    <p class="txt center">পত্রহীন বৃক্ষশাখে,</p>
    <p class="txt center">রাত্রির শেষে পূর্বদিগন্তে</p>
    <p class="txt center"><span>প্রভাত অরুণ হাসে</span><span>—</span></p>
    <p class="txt center">জাগে ফুলদল, আনন্দ পাখিরা ডাকে।</p>
    <p class="txt center">মানবতার জয় একদিন হবে</p>
    <p class="txt center">হবে রে হৃদয়ের জয়,</p>
    <p class="txt center">এই গ্রহে চিরশান্তি আসবেই তবে</p>
    <p class="txt center">দানবের যেদিন হবে রে লয়।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center"><span>সেইদিন আর বেশি দূরে নাই, শুনি</span><span>—</span></p>
    <p class="txt center">শুনি সম্মুখে সময়েরা গর্জায়,</p>
    <p class="txt center"><span>সেদিনের তরে আমি দিন গুনি</span><span>—</span></p>
    <p class="txt center">পুরাতন ইতিহাস ভেঙ্গে আসবে নতুন পর্যায়।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">বনভন্তের-স্তুতি</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">তুমি চিরউজ্জল রবিকর</p>
    <p class="txt center">মানবচিতত্তগগন মাঝে,</p>
    <p class="txt center">কালজয়ী তুমি কালের প্রবাহে</p>
    <p class="txt center">মানবসকল তব বন্দনা-গীতি গাহে</p>
    <p class="txt center"><span>জীবনপ্রভাত দ্বিপ্রহর সাঁঝে</span><span>—</span></p>
    <p class="txt center">তুমি চিরউজ্জল রবিকর</p>
    <p class="txt center">মানবচিতত্তগগন মাঝে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">তুমি সতত বিরাজ হৃদে</p>
    <p class="txt center">চিত্তচৈতন্য গভীর গহীনে,</p>
    <p class="txt center">তুমি যে আলোর পথদিশারী</p>
    <p class="txt center">মানবহৃদে নিভৃতে দিবানিশি বিহারী</p>
    <p class="txt center"><span>সকল জনসখা সুখ-দুঃখ দিনে</span><span>—</span></p>
    <p class="txt center">তুমি সতত বিরাজ হৃদে</p>
    <p class="txt center">চিত্তচৈতন্য গভীর গহীনে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">চিরঞ্জীব তুমি অক্ষয় অমলিন</p>
    <p class="txt center">কালে কালে মানবের প্রাণে,</p>
    <p class="txt center">সহসা পৌঁছি তব আলোকরাশি</p>
    <p class="txt center">প্রাণের সকল তিমির সহসা নাশি</p>
    <p class="txt center"><span>ভরে মন পুষ্প হেন সুবাসিত ঘ্রাণে</span><span>—</span></p>
    <p class="txt center">চিরঞ্জীব তুমি অক্ষয় অমলিন</p>
    <p class="txt center">কালে কালে মানবের প্রাণে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">তব হিতবাণী অনন্ত উদার</p>
    <p class="txt center">বিশ্বমানবের শান্তির তরে,</p>
    <p class="txt center">সময়ের স্রোতে কাল যায় আসে</p>
    <p class="txt center">তব মহিমা পুষ্পসম সতত বিকাশে</p>
    <p class="txt center"><span>ষড়রিপুভরা এ ধরণীর 'পরে</span><span>—</span></p>
    <p class="txt center">তব হিতবাণী অনন্ত উদার</p>
    <p class="txt center">বিশ্বমানবের শান্তির তরে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">গরিমা তোমার অপার সিন্ধু</p>
    <p class="txt center">করুণার বিশ্ব করেছ জয়,</p>
    <p class="txt center">অকাতরে করুণাধারা দিয়েছ ঢেলে</p>
    <p class="txt center">অন্ধজনের বন্ধ দু'চোখ দিয়েছ মেলে</p>
    <p class="txt center"><span>নাহি নাহি কভূ নাহি তারি ক্ষয়</span><span>—</span></p>
    <p class="txt center">গরিমা তোমার অপার সিন্ধু</p>
    <p class="txt center">করুণার বিশ্ব করেছ জয়।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">পার্থিব যত সুখ তুচ্ছ করি</p>
    <p class="txt center">করেছ কঠোর সাধনা-ধ্যান,</p>
    <p class="txt center">ত্যাগই মরমে পরম প্রশান্তি আনে</p>
    <p class="txt center">ভোগই নিয়ত তৃষ্ণার অস্থিরতা হানে</p>
    <p class="txt center"><span>লভেছ নিগূঢ় পরম সত্যজ্ঞান</span><span>—</span></p>
    <p class="txt center">পার্থিব যত সুখ তুচ্ছ করি</p>
    <p class="txt center">করেছ কঠোর সাধনা-ধ্যান।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">তুমি আর্যশ্রেষ্ঠ তুমি পুরুষোত্তম</p>
    <p class="txt center">তুমি বৌদ্ধ জাতির গৌরব,</p>
    <p class="txt center">ধীর করিবারে আপন অধীর</p>
    <p class="txt center">দানিয়াছ হিতোপদেশ মানবেরে নিত্য</p>
    <p class="txt center"><span>বিলায়েছ পুষ্পরেণুসম সদ্ধর্মসৌরভ</span><span>—</span></p>
    <p class="txt center">তুমি আর্যশ্রেষ্ঠ তুমি পুরুষোত্তম</p>
    <p class="txt center">তুমি বৌদ্ধ জাতির গৌরব।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">তুমি মহাজ্ঞানী তুমি মহাধ্যানী</p>
    <p class="txt center">লভিয়াছ পরম সুখ নির্বাণ,</p>
    <p class="txt center">তুমি রচিয়াছ ভুবনে অমর সঙ্গীত</p>
    <p class="txt center">আত্মজয় প্রশান্তির শ্রেষ্ঠতম ভিত</p>
    <p class="txt center"><span>মানবভুবনে তুমি চিরদ্যুতিমান</span><span>—</span></p>
    <p class="txt center">তুমি মহাজ্ঞানী তুমি মহাধ্যানী</p>
    <p class="txt center">লভিয়াছ পরম সুখ নির্বাণ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">তুমি চিরস্মরণীয় তুমি চিরপূজনীয়</p>
    <p class="txt center">তুমি পরম ধর্মসারথি,</p>
    <p class="txt center">তুমি আমলিন তুমি চিরভাস্বর</p>
    <p class="txt center">তব হিতবাণী চির-অবিনস্বর</p>
    <p class="txt center"><span>মনে আনে সুখ, নাশি পার্থিব আরতি</span><span>—</span></p>
    <p class="txt center">তুমি চিরস্মরণীয় তুমি চিরপূজনীয়</p>
    <p class="txt center">তুমি পরম ধর্মসারথি।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">জীবনবোধের পদাবলি</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">১.</p>
    <p class="txt center">আপনাতে সুখ</p>
    <p class="txt center"><span>আপনাতে দুঃখ</span><span>—</span></p>
    <p class="txt center">আপনাতেই সবকিছু মিলে,</p>
    <p class="txt center">তবুও অবুজ মন,</p>
    <p class="txt center"><span>হায়, খুঁজে সুখ হেথা হোথা</span><span>—</span></p>
    <p class="txt center">দহে তিলে তিলে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">২.</p>
    <p class="txt center">এখানে দাঁড়াও,</p>
    <p class="txt center"><span>হে চঞ্চল পথিক</span><span>—</span></p>
    <p class="txt center">স্থির রও</p>
    <p class="txt center"><span>ভ্রষ্টাচারী না হও</span><span>—</span></p>
    <p class="txt center">ধীর লয়ে চরণ বাড়াও,</p>
    <p class="txt center">হও নির্ভীক।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">৩.</p>
    <p class="txt center">সময় তো বয়েই যায়,</p>
    <p class="txt center">সেই সাথে ক্ষয়ে যায়</p>
    <p class="txt center">দুর্লভ জনমের আয়ু;</p>
    <p class="txt center">জীবন হোক কুসুমের মত,</p>
    <p class="txt center">না হোক নিষ্ফল যেন</p>
    <p class="txt center">চৈত্রদিনের তপ্ত ঘূর্ণিবায়ু।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">৪.</p>
    <p class="txt center">আপন আপন বলো,</p>
    <p class="txt center">বলো কে তোমার?</p>
    <p class="txt center"><span>আপনই আপনার আপন</span><span>—</span></p>
    <p class="txt center">পৃথিবীতে আপন আর নেই কোনোজন।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">নিব্বানং</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">জন্ম নাই মৃত্যু নাই</p>
    <p class="txt center">নাই শুরু নাই শেষ</p>
    <p class="txt center">সুখ নাই দুঃখ নাই</p>
    <p class="txt center">নাই আনন্দ বেদনা-ক্লেশ</p>
    <p class="txt center">রূপ নাই রং নাই</p>
    <p class="txt center">অনুভূতি নাই</p>
    <p class="txt center">নাই কোনো আশা</p>
    <p class="txt center">স্বাদ নাই গন্ধ নাই</p>
    <p class="txt center"><span>গতি নাই</span><span>—</span><span>নাই ভালোবাসা</span></p>
    <p class="txt center">আলো নাই আঁধার নাই</p>
    <p class="txt center">নাই দিন কিবা রাত্রি</p>
    <p class="txt center">সময়ের সেতু নাই</p>
    <p class="txt center">নাই এপার-ওপারের যাত্রী</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">কোনো কামনা-বাসনা নাই</p>
    <p class="txt center">নাই পাপ কিবা পুণ্য</p>
    <p class="txt center">অনন্ত শূন্যে মিশিয়া যাওয়া</p>
    <p class="txt center">করিয়া নিজেরে সকলি শূন্য</p>
    <p class="txt center">বিশাল অনন্ত শূন্য</p>
    <p class="txt center">মুক্ত বন্ধনহীন</p>
    <p class="txt center">তৃষ্ণামুক্ত পাপমুক্ত</p>
    <p class="txt center">জন্ম মৃত্যু বিলীন</p>
    <p class="txt center">জন্ম-মৃত্যু কামনা-বাসনা</p>
    <p class="txt center">রুদ্ধ সকল দ্বার</p>
    <p class="txt center">কোনো আয়োজন নাই</p>
    <p class="txt center">পুনঃজনম লভিবার</p>
    <p class="txt center">শূন্য শূন্য অনন্ত শূন্য</p>
    <p class="txt center"><span>শূন্য করো চিত্তখানি</span><span>—</span></p>
    <p class="txt center">'নিব্বানং পরমং সুখং'</p>
    <p class="txt center">তথাগত বুদ্ধবাণী।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">&nbsp;</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">এই অনিত্য ভুবনে</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">আমি আমি বলি সবে</p>
    <p class="txt center">আমার আমার কই</p>
    <p class="txt center">আমি আর আমাতে সদাই</p>
    <p class="txt center">মজিয়া মাতিয়া রই!</p>
    <p class="txt center">আমিতে আমিত্ব যত</p>
    <p class="txt center">অন্যতে নাহি মানামানি,</p>
    <p class="txt center">আমার আমার বলে</p>
    <p class="txt center">হায়, কত হানাহানি!</p>
    <p class="txt center">কেহ উচ্চ, কেহ হীন</p>
    <p class="txt center">মানবে যত শ্রেণিভেদ,</p>
    <p class="txt center"><span>জাগায় অন্তর দহন</span><span>—</span></p>
    <p class="txt center">মনেতে গভীর খেদ!</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">বিশ্বব্রহ্মাণ্ডে সকলি ক্ষণিক</p>
    <p class="txt center">সকলি অনিত্য অসার,</p>
    <p class="txt center">ইহকাল ছাড়ি' পরকাল</p>
    <p class="txt center">খোঁজ কেবা রাখে কার?</p>
    <p class="txt center">ইহকালে কত না প্রতাপ</p>
    <p class="txt center">কত না অহংকার,</p>
    <p class="txt center">পাপ-পুণ্য সাথে শুধু</p>
    <p class="txt center">এপার হতে ওপার।</p>
    <p class="txt center">শত জনমের পুণ্যের ফল</p>
    <p class="txt center">এ মানবজনম পাওয়া,</p>
    <p class="txt center">এ জনম কেনরে তবে</p>
    <p class="txt center">বৃথাই বিফলে যাওয়া?</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">এসো, জ্যোতির্ময় প্রজ্ঞালোকে</p>
    <p class="txt center">ঋদ্ধ করি আপনারে,</p>
    <p class="txt center">নিকষ আঁধারে যেজন</p>
    <p class="txt center">দীপ্ত করি তারে।</p>
    <p class="txt center">হেলা নয় ঘৃণা নয়</p>
    <p class="txt center">তারে ভালোবাসি,</p>
    <p class="txt center">অজ্ঞান-অন্ধকার তার</p>
    <p class="txt center">আলোর পরশে নাশি।</p>
    <p class="txt center">মুছে যাক মনের আঁধার</p>
    <p class="txt center">যত হিংসা-নিন্দা-ক্রোধ,</p>
    <p class="txt center"><span>শান্ত হোক উতল প্রাণ</span><span>—</span></p>
    <p class="txt center">জাগুক শুভ্র আলোকবোধ।</p>
    <p class="txt center">এই অনিত্য ভুবনে, হেথা</p>
    <p class="txt center">শুধু আলোকের কথা কই,</p>
    <p class="txt center">মানবের মন হতে মনে</p>
    <p class="txt center">তারা হয়ে হেগে রই।</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">তুমি এক আলোকশিখা</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">(প্রয়াত চাকমা রাজগুরু অগ্রবংশ মহাস্থবির উদ্দেশে)</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">তুমি জানতে তোমার একদিন চলে যাওয়া হবে;</p>
    <p class="txt center">এখানে যার আসা হয়</p>
    <p class="txt center">একদিন চলেও যাওয়া হয় তার;</p>
    <p class="txt center"><span>এই আসা এই যাওয়া</span><span>—</span></p>
    <p class="txt center">মাঝখানে সময়ের খরস্রোতা নদী,</p>
    <p class="txt center"><span>কেউ ভাসে</span><span>—</span><span>কেউ ডুবে</span><span>—</span></p>
    <p class="txt center">কেউ যায় ভেসে;</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">তোমার নৌকো ছিল,</p>
    <p class="txt center"><span>ছিল ধবধবে সাদা পাল</span><span>—</span></p>
    <p class="txt center">পালে লেগেছিল জ্যোতির্ময় হাওয়া;</p>
    <p class="txt center">আমরা তখন ঘোর অন্ধকারে</p>
    <p class="txt center">কর্ণধারহীন নৌকোয় নিরুদ্দেশ যাত্রী যেন;</p>
    <p class="txt center">তুমি এসেছিলে সেই দুঃসময়ে</p>
    <p class="txt center">সাথে ছিল গৌতমের সুবর্ণ আলো</p>
    <p class="txt center"><span>আর তোমার কালজয়ী আত্মজ বিশ্বাস</span><span>—</span></p>
    <p class="txt center">আমরা আকন্ঠ পান করলাম</p>
    <p class="txt center">তোমার সেই নবীন কন্ঠে ধ্বনিত</p>
    <p class="txt center">অবিনাশী কবিতার বিশুদ্ধ পঙ্ক্তিমালা;</p>
    <p class="txt center">অতঃপর, আমরা</p>
    <p class="txt center"><span>গঙ্গাস্নান সেরে উঠে এলাম ডাঙায়</span><span>—</span></p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">আমরা জেনেছি,</p>
    <p class="txt center"><span>উজ্জ্বলতায় ঋদ্ধ তুমি এক আলোকশিখা</span><span>—</span></p>
    <p class="txt center">তুমি অবিনাশী।</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">ইচ্ছে-ঘুড়ি</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">মনের আকাশ মেঘলা, তবু</p>
    <p class="txt center">তৃষ্ণারা উড়ায় ঘুড়ি,</p>
    <p class="txt center">ইচ্ছেরা সব মেঘের কোলে</p>
    <p class="txt center">দিচ্ছে হামাগুড়ি।</p>
    <p class="txt center"><span>তীব্র চাওয়া ক্ষিপ্র হাওয়া</span><span>—</span></p>
    <p class="txt center">মেলছে ডানা ইচ্ছে,</p>
    <p class="txt center">তৃষ্ণারা সব কলজেটাতে</p>
    <p class="txt center">ভোগের কামড় দিচ্ছে।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">নেইকো সময় কিম্বা বয়স</p>
    <p class="txt center"><span>তৃষ্ণারা  উড়ায় ঘুড়ি,</span></p>
    <p class="txt center">হোক সেই কিশোর কিম্বা জোয়ান</p>
    <p class="txt center">হোক সে বুড়ো-বুড়ি।</p>
    <p class="txt center">জন্ম থেকেই ইচ্ছেগুলোর</p>
    <p class="txt center">ডানা গজায় কেবল,</p>
    <p class="txt center">দুধ কলাতে পুছে রাখা</p>
    <p class="txt center">মারে বিষের ছোবল!</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center"><span>সোজা যদি না হয় চলন</span><span>—</span></p>
    <p class="txt center">হয় যদি গো বাঁকা,</p>
    <p class="txt center">ছোবল যদি মারল তবে</p>
    <p class="txt center">কেনরে পুছে রাখ?</p>
    <p class="txt center">তৃষ্ণা যে এক মরুর সাগর</p>
    <p class="txt center">চায় সে শুধু জল,</p>
    <p class="txt center">এক নিমিষেই যায় শুকিয়ে</p>
    <p class="txt center">নাই কোনো তার তল!</p>
    <p class="txt center">চাওয়া পাওয়ার মাঝখানেতে</p>
    <p class="txt center">মরু মরুই থাকে,</p>
    <p class="txt center">মন্দ-ভালোর হিসাব-নিকাশ</p>
    <p class="txt center">কজনেই-বা রাখে?</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center"><span>ইচ্ছে-ঘুড়ি উড়ানো ভালো</span><span>—</span></p>
    <p class="txt center">তবে সাবধানেতে থাকা,</p>
    <p class="txt center">বেপরোয়া যেন না হয় ঘুড়ি</p>
    <p class="txt center">নাটাই নিজের হাতেই রাখ।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">মন-খিড়কিতে হরেক রকম</p>
    <p class="txt center">তৃষ্ণারা দেয় উঁকি,</p>
    <p class="txt center"><span>তৃষ্ণাই যত দুঃখ ভোগায়</span><span>—</span></p>
    <p class="txt center">আত্মসংযমীরাই সুখ।</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">আসা যাওয়ার এই ভুবনে</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center"><span>তব যত দুঃখ, হে বন্ধু, আমায় দাও</span><span>—</span></p>
    <p class="txt center">দুঃখের বোঝা যে আমি বই,</p>
    <p class="txt center">এ জনমের যত যাতনা</p>
    <p class="txt center">নীরবে নিভৃতিতে সই।</p>
    <p class="txt center">দুঃখ আমার চির জনমের সাথী</p>
    <p class="txt center">দুঃখের সাথে করি বসবাস,</p>
    <p class="txt center">যেথা আমি ফসলের বীজ বুনি</p>
    <p class="txt center">বন্যার জল মোরে করে পরিহাস।</p>
    <p class="txt center">আমি জানিয়াছি, এ জীবন শুধু</p>
    <p class="txt center">খেলে যাওয়া দুঃখের খেলা,</p>
    <p class="txt center">কেটে যাবে দিন, মেঘে মেঘে</p>
    <p class="txt center">আমার সকাল-সন্ধ্যাবেলা।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center">সুন্দর সোনালি ফসলের লোভে</p>
    <p class="txt center">নদীতীরে বারবার বাঁধিয়াছি ঘর,</p>
    <p class="txt center">জলস্রোতে সবই যায় ভেসে,</p>
    <p class="txt center">সবে যেন একে একে হয়ে যায় পর।</p>
    <p class="txt center">কেহ দুঃখ কেহ অপবাদ</p>
    <p class="txt center">দেয় কেহ-বা ঘৃণা,</p>
    <p class="txt center">সময়ের বাঁকে ঘূর্ণির পাকে</p>
    <p class="txt center">তবু ভাঙে নাই হৃদয়বীণা।</p>
    <p class="txt center">আমার বাহির পানে সকলে দেখিল</p>
    <p class="txt center">অন্তর মম কেহ দেখিল না,</p>
    <p class="txt center">আমারে লইয়া সবে খেলিল</p>
    <p class="txt center">হৃদয়ের কথা কেহ বুঝিল না।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center"><span>কোন পার হতে আসিয়াছি</span><span>—</span></p>
    <p class="txt center">দিবা শেষে কোথা-বা যাওয়া,</p>
    <p class="txt center">আসা আর যাওয়ার জই ভুবনে</p>
    <p class="txt center">মিছেমিছি, হায়, এ কেমন দুঃখ পাওয়া।</p>
    <p class="txt center">এ জীবন এই আছে এই নাই</p>
    <p class="txt center">যেন-বা বন্যার ধেয়ে আসা ঘোলা জল,</p>
    <p class="txt center"><span>মিছে আশা</span><span>—</span><span>মিছে হাসা</span><span>—</span><span>সব মিছে</span></p>
    <p class="txt center">মিছে সব নদীর বুকে তরঙ্গ উচ্ছ্বল।</p>
    <p class="txt center">&nbsp;</p>
    <p class="txt center"><span>হে প্রিয়, হে বন্ধু মোর</span><span>—</span></p>
    <p class="txt center">দাও তব দুঃখপাত্র উজার করি,</p>
    <p class="txt center">ক্ষুদ্র এ বুকে বিশাল সিন্ধু মম</p>
    <p class="txt center"><span>উঠুক কানায় কানায় ভরি</span><span>—</span></p>
    <p class="txt center"><span>হৃদয়ের যত তাপ দহে চিতাগ্নিসম;</span><span>—</span></p>
    <p class="txt center">সিন্ধু জলে করি শুচিস্নান</p>
    <p class="txt center">যত তুচ্ছ সুখরাশি হোক অবসান।</p>
    </div>
    <div class="react">
    </div>
    </div>
    <h1 class="title">নাম</h1>
    <div class="post_box">
    <div class="post_txt">
    <p class="txt center">&nbsp;</p>
    <p class="txt center">আমার নাম অমল হতে পারত,</p>
    <p class="txt center">হতে পারত বিমল</p>
    <p class="txt center">অথবা কমল</p>
    <p class="txt center">অথবা অন্য কোনো নাম;</p>
    <p class="txt center">আমি বলি,</p>
    <p class="txt center"><span>নামে কী-বা আসে-যায়</span><span>—</span></p>
    <p class="txt center">জীবন তো নয় সুখময়,</p>
    <p class="txt center">বরং দুঃখময়;</p>
    <p class="txt center">এবং মৃত্যুই তার</p>
    <p class="txt center">অনিবার্য পরিণাম।</p>
    </div>
    <div class="react">
    </div>
    </div>
      
`;
var url = location.href.includes('app.html')
if(!url){
    console.log(url)
    document.getElementById('post_container').innerHTML = post_txt
    readhelper();
}